
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d069a162819eee1beff138a34cdb6e81825395e9",
 "version": "0.5.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
