
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-26T14:28:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2667a5befe8cf3acde1a0bf1a3faf0fb119aeb9",
 "version": "v22.12.00a220927"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
