
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-01T14:36:17-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9268ddaf9f18d8b511301afbdb31bf7041854c3d",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
