# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x12messagev.orchestsh\"L\n\x0e\x43ommandRequest\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ommand_name\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\x0c\"\x88\x01\n\x0f\x43ommandResponse\x12@\n\x06status\x18\x01 \x01(\x0e\x32\x30.messagev.orchestsh.CommandResponse.StatusOption\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\"&\n\x0cStatusOption\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMANDREQUEST._serialized_start=37
  _COMMANDREQUEST._serialized_end=113
  _COMMANDRESPONSE._serialized_start=116
  _COMMANDRESPONSE._serialized_end=252
  _COMMANDRESPONSE_STATUSOPTION._serialized_start=214
  _COMMANDRESPONSE_STATUSOPTION._serialized_end=252
# @@protoc_insertion_point(module_scope)
