'''__init__.py'''


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._929 import AddendumModificationDistributionRule
    from ._930 import BacklashSpecification
    from ._931 import BasicRackProfiles
    from ._932 import CaseHardeningProperties
    from ._933 import CreateNewSuitableCutterOption
    from ._934 import CrossedAxisCylindricalGearPair
    from ._935 import CrossedAxisCylindricalGearPairLineContact
    from ._936 import CrossedAxisCylindricalGearPairPointContact
    from ._937 import CylindricalGearAbstractRack
    from ._938 import CylindricalGearAbstractRackFlank
    from ._939 import CylindricalGearBasicRack
    from ._940 import CylindricalGearBasicRackFlank
    from ._941 import CylindricalGearCuttingOptions
    from ._942 import CylindricalGearDefaults
    from ._943 import CylindricalGearDesign
    from ._944 import CylindricalGearDesignConstraint
    from ._945 import CylindricalGearDesignConstraints
    from ._946 import CylindricalGearDesignConstraintsDatabase
    from ._947 import CylindricalGearDesignConstraintSettings
    from ._948 import CylindricalGearDesignSettings
    from ._949 import CylindricalGearFlankDesign
    from ._950 import CylindricalGearMeshDesign
    from ._951 import CylindricalGearMeshFlankDesign
    from ._952 import CylindricalGearPinionTypeCutter
    from ._953 import CylindricalGearPinionTypeCutterFlank
    from ._954 import CylindricalGearProfileMeasurement
    from ._955 import CylindricalGearProfileMeasurementType
    from ._956 import CylindricalGearProfileModifications
    from ._957 import CylindricalGearSetDesign
    from ._958 import CylindricalGearSetFlankDesign
    from ._959 import CylindricalGearSetMacroGeometryOptimiser
    from ._960 import CylindricalGearSetManufacturingConfigurationSelection
    from ._961 import CylindricalGearTableMGItemDetail
    from ._962 import CylindricalGearTableWithMGCharts
    from ._963 import CylindricalGearToothThicknessSpecification
    from ._964 import CylindricalMeshAngularBacklash
    from ._965 import CylindricalMeshedGear
    from ._966 import CylindricalMeshedGearFlank
    from ._967 import CylindricalMeshLinearBacklashSpecification
    from ._968 import CylindricalPlanetaryGearSetDesign
    from ._969 import CylindricalPlanetGearDesign
    from ._970 import DIN3967AllowanceSeries
    from ._971 import DIN3967ToleranceSeries
    from ._972 import FinishStockSpecification
    from ._973 import FinishToothThicknessDesignSpecification
    from ._974 import GearFitSystems
    from ._975 import GearManufacturingConfigSetupViewModel
    from ._976 import GearSetFCAImportSetup
    from ._977 import GearSetManufacturingConfigurationSetup
    from ._978 import GeometrySpecificationType
    from ._979 import HardenedMaterialProperties
    from ._980 import HardnessProfileCalculationMethod
    from ._981 import HeatTreatmentType
    from ._982 import ISO6336Geometry
    from ._983 import ISO6336GeometryBase
    from ._984 import ISO6336GeometryForShapedGears
    from ._985 import ISO6336GeometryManufactured
    from ._986 import LinearBacklashSepcification
    from ._987 import LTCALoadCaseModifiableSettings
    from ._988 import LtcaSettings
    from ._989 import MicroGeometryConvention
    from ._990 import MicroGeometryProfileConvention
    from ._991 import Micropitting
    from ._992 import NamedPlanetAssemblyIndex
    from ._993 import NamedPlanetSideBandAmplitudeFactor
    from ._994 import ReadonlyToothThicknessSpecification
    from ._995 import RelativeMeasurementViewModel
    from ._996 import RelativeValuesSpecification
    from ._997 import Scuffing
    from ._998 import ScuffingCoefficientOfFrictionMethods
    from ._999 import ScuffingTemperatureMethodsAGMA
    from ._1000 import ScuffingTemperatureMethodsISO
    from ._1001 import ShaperEdgeTypes
    from ._1002 import SpurGearLoadSharingCodes
    from ._1003 import StandardRack
    from ._1004 import StandardRackFlank
    from ._1005 import SurfaceRoughness
    from ._1006 import ThicknessType
    from ._1007 import TiffAnalysisSettings
    from ._1008 import TipAlterationCoefficientMethod
    from ._1009 import TolerancedMetalMeasurements
    from ._1010 import TolerancedValueSpecification
    from ._1011 import ToothThicknessSpecification
    from ._1012 import ToothThicknessSpecificationBase
    from ._1013 import TypeOfMechanismHousing
    from ._1014 import Usage
