# list of useful stop words to identify negative impact
exclude_words = [
    "against",
    "not",
    "don",
    "don't",
    "ain",
    "aren",
    "aren't",
    "couldn",
    "couldn't",
    "didn",
    "didn't",
    "doesn",
    "doesn't",
    "hadn",
    "hadn't",
    "hasn",
    "hasn't",
    "haven",
    "haven't",
    "isn",
    "isn't",
    "mightn",
    "mightn't",
    "mustn",
    "mustn't",
    "needn",
    "needn't",
    "shouldn",
    "shouldn't",
    "wasn",
    "wasn't",
    "weren",
    "weren't",
    "won",
    "won't",
    "wouldn",
    "wouldn't",
]

# list of timezones
time_zones = [
    "ACDT",
    "ACST",
    "ACT",
    "ACT",
    "ACWST",
    "ADT",
    "AEDT",
    "AEST",
    "AET",
    "AFT",
    "AKDT",
    "AKST",
    "ALMT",
    "AMST",
    "AMT",
    "AMT",
    "ANAT",
    "AQTT",
    "ART",
    "AST",
    "AST",
    "AWST",
    "AZOST",
    "AZOT",
    "AZT",
    "BDT",
    "BIOT",
    "BIT",
    "BOT",
    "BRST",
    "BRT",
    "BST",
    "BST",
    "BST",
    "BTT",
    "CAT",
    "CCT",
    "CDT",
    "CDT",
    "CEST",
    "CET",
    "CHADT",
    "CHAST",
    "CHOT",
    "CHOST",
    "CHST",
    "CHUT",
    "CIST",
    "CIT",
    "CKT",
    "CLST",
    "CLT",
    "COST",
    "COT",
    "CST",
    "CST",
    "CST",
    "CT",
    "CVT",
    "CWST",
    "CXT",
    "DAVT",
    "DDUT",
    "DFT",
    "EASST",
    "EAST",
    "EAT",
    "ECT",
    "ECT",
    "EDT",
    "EEST",
    "EET",
    "EGST",
    "EGT",
    "EIT",
    "EST",
    "FET",
    "FJT",
    "FKST",
    "FKT",
    "FNT",
    "GALT",
    "GAMT",
    "GET",
    "GFT",
    "GILT",
    "GIT",
    "GMT",
    "GST",
    "GST",
    "GYT",
    "HDT",
    "HAEC",
    "HST",
    "HKT",
    "HMT",
    "HOVST",
    "HOVT",
    "ICT",
    "IDLW",
    "IDT",
    "IOT",
    "IRDT",
    "IRKT",
    "IRST",
    "IST",
    "IST",
    "IST",
    "JST",
    "KALT",
    "KGT",
    "KOST",
    "KRAT",
    "KST",
    "LHST",
    "LHST",
    "LINT",
    "MAGT",
    "MART",
    "MAWT",
    "MDT",
    "MET",
    "MEST",
    "MHT",
    "MIST",
    "MIT",
    "MMT",
    "MSK",
    "MST",
    "MST",
    "MUT",
    "MVT",
    "MYT",
    "NCT",
    "NDT",
    "NFT",
    "NOVT",
    "NPT",
    "NST",
    "NT",
    "NUT",
    "NZDT",
    "NZST",
    "OMST",
    "ORAT",
    "PDT",
    "PET",
    "PETT",
    "PGT",
    "PHOT",
    "PHT",
    "PKT",
    "PMDT",
    "PMST",
    "PONT",
    "PST",
    "PST",
    "PYST",
    "PYT",
    "RET",
    "ROTT",
    "SAKT",
    "SAMT",
    "SAST",
    "SBT",
    "SCT",
    "SDT",
    "SGT",
    "SLST",
    "SRET",
    "SRT",
    "SST",
    "SST",
    "SYOT",
    "TAHT",
    "THA",
    "TFT",
    "TJT",
    "TKT",
    "TLT",
    "TMT",
    "TRT",
    "TOT",
    "TVT",
    "ULAST",
    "ULAT",
    "UTC",
    "UYST",
    "UYT",
    "UZT",
    "VET",
    "VLAT",
    "VOLT",
    "VOST",
    "VUT",
    "WAKT",
    "WAST",
    "WAT",
    "WEST",
    "WET",
    "WIT",
    "WGST",
    "WGT",
    "WST",
    "YAKT",
    "YEKT",
]

# Map of contractions and their corresponding values
contractions_map = {
    "ain't": "is not",
    "aren't": "are not",
    "can't": "cannot",
    "can't've": "cannot have",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "couldn't've": "could not have",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hadn't've": "had not have",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'd've": "he would have",
    "he'll": "he will",
    "he'll've": "he he will have",
    "he's": "he is",
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "how's": "how is",
    "I'd": "I would",
    "I'd've": "I would have",
    "I'll": "I will",
    "I'll've": "I will have",
    "I'm": "I am",
    "I've": "I have",
    "i'd": "i would",
    "i'd've": "i would have",
    "i'll": "i will",
    "i'll've": "i will have",
    "i'm": "i am",
    "i've": "i have",
    "isn't": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it'll've": "it will have",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she would",
    "she'd've": "she would have",
    "she'll": "she will",
    "she'll've": "she will have",
    "she's": "she is",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so as",
    "that'd": "that would",
    "that'd've": "that would have",
    "that's": "that is",
    "there'd": "there would",
    "there'd've": "there would have",
    "there's": "there is",
    "they'd": "they would",
    "they'd've": "they would have",
    "they'll": "they will",
    "they'll've": "they will have",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what'll've": "what will have",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who's": "who is",
    "who've": "who have",
    "why's": "why is",
    "why've": "why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you would",
    "you'd've": "you would have",
    "you'll": "you will",
    "you'll've": "you will have",
    "you're": "you are",
    "you've": "you have",
}