# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_woodpecker/woodpecker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from th2_grpc_common import common_pb2 as th2__grpc__common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='th2_grpc_woodpecker/woodpecker.proto',
  package='woodpecker',
  syntax='proto3',
  serialized_options=b'\n com.exactpro.th2.woodpecker.grpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$th2_grpc_woodpecker/woodpecker.proto\x12\nwoodpecker\x1a\x1cth2_grpc_common/common.proto\"Q\n\x0cStartRequest\x12\x0c\n\x04rate\x18\x01 \x01(\r\x12\x10\n\x08settings\x18\x02 \x01(\t\x12!\n\x0fparent_event_id\x18\x03 \x01(\x0b\x32\x08.EventID\"\xaf\x01\n\x0fScheduleRequest\x12\x0e\n\x06\x63ycles\x18\x01 \x01(\r\x12/\n\x05steps\x18\x02 \x03(\x0b\x32 .woodpecker.ScheduleRequest.Step\x12!\n\x0fparent_event_id\x18\x03 \x01(\x0b\x32\x08.EventID\x1a\x38\n\x04Step\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\x12\x0c\n\x04rate\x18\x02 \x01(\r\x12\x10\n\x08settings\x18\x03 \x01(\t\"\r\n\x0bStopRequest\"l\n\x08Response\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.woodpecker.Response.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\xbb\x01\n\nWoodpecker\x12\x37\n\x05start\x12\x18.woodpecker.StartRequest\x1a\x14.woodpecker.Response\x12=\n\x08schedule\x12\x1b.woodpecker.ScheduleRequest\x1a\x14.woodpecker.Response\x12\x35\n\x04stop\x12\x17.woodpecker.StopRequest\x1a\x14.woodpecker.ResponseB$\n com.exactpro.th2.woodpecker.grpcP\x01\x62\x06proto3'
  ,
  dependencies=[th2__grpc__common_dot_common__pb2.DESCRIPTOR,])



_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='woodpecker.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=432,
  serialized_end=466,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)


_STARTREQUEST = _descriptor.Descriptor(
  name='StartRequest',
  full_name='woodpecker.StartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rate', full_name='woodpecker.StartRequest.rate', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='settings', full_name='woodpecker.StartRequest.settings', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent_event_id', full_name='woodpecker.StartRequest.parent_event_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=163,
)


_SCHEDULEREQUEST_STEP = _descriptor.Descriptor(
  name='Step',
  full_name='woodpecker.ScheduleRequest.Step',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='woodpecker.ScheduleRequest.Step.duration', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rate', full_name='woodpecker.ScheduleRequest.Step.rate', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='settings', full_name='woodpecker.ScheduleRequest.Step.settings', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=341,
)

_SCHEDULEREQUEST = _descriptor.Descriptor(
  name='ScheduleRequest',
  full_name='woodpecker.ScheduleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cycles', full_name='woodpecker.ScheduleRequest.cycles', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steps', full_name='woodpecker.ScheduleRequest.steps', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent_event_id', full_name='woodpecker.ScheduleRequest.parent_event_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SCHEDULEREQUEST_STEP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=341,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='woodpecker.StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=356,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='woodpecker.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='woodpecker.Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='woodpecker.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=466,
)

_STARTREQUEST.fields_by_name['parent_event_id'].message_type = th2__grpc__common_dot_common__pb2._EVENTID
_SCHEDULEREQUEST_STEP.containing_type = _SCHEDULEREQUEST
_SCHEDULEREQUEST.fields_by_name['steps'].message_type = _SCHEDULEREQUEST_STEP
_SCHEDULEREQUEST.fields_by_name['parent_event_id'].message_type = th2__grpc__common_dot_common__pb2._EVENTID
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE_STATUS.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['StartRequest'] = _STARTREQUEST
DESCRIPTOR.message_types_by_name['ScheduleRequest'] = _SCHEDULEREQUEST
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'th2_grpc_woodpecker.woodpecker_pb2'
  # @@protoc_insertion_point(class_scope:woodpecker.StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

ScheduleRequest = _reflection.GeneratedProtocolMessageType('ScheduleRequest', (_message.Message,), {

  'Step' : _reflection.GeneratedProtocolMessageType('Step', (_message.Message,), {
    'DESCRIPTOR' : _SCHEDULEREQUEST_STEP,
    '__module__' : 'th2_grpc_woodpecker.woodpecker_pb2'
    # @@protoc_insertion_point(class_scope:woodpecker.ScheduleRequest.Step)
    })
  ,
  'DESCRIPTOR' : _SCHEDULEREQUEST,
  '__module__' : 'th2_grpc_woodpecker.woodpecker_pb2'
  # @@protoc_insertion_point(class_scope:woodpecker.ScheduleRequest)
  })
_sym_db.RegisterMessage(ScheduleRequest)
_sym_db.RegisterMessage(ScheduleRequest.Step)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQUEST,
  '__module__' : 'th2_grpc_woodpecker.woodpecker_pb2'
  # @@protoc_insertion_point(class_scope:woodpecker.StopRequest)
  })
_sym_db.RegisterMessage(StopRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'th2_grpc_woodpecker.woodpecker_pb2'
  # @@protoc_insertion_point(class_scope:woodpecker.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_WOODPECKER = _descriptor.ServiceDescriptor(
  name='Woodpecker',
  full_name='woodpecker.Woodpecker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=469,
  serialized_end=656,
  methods=[
  _descriptor.MethodDescriptor(
    name='start',
    full_name='woodpecker.Woodpecker.start',
    index=0,
    containing_service=None,
    input_type=_STARTREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='schedule',
    full_name='woodpecker.Woodpecker.schedule',
    index=1,
    containing_service=None,
    input_type=_SCHEDULEREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='stop',
    full_name='woodpecker.Woodpecker.stop',
    index=2,
    containing_service=None,
    input_type=_STOPREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WOODPECKER)

DESCRIPTOR.services_by_name['Woodpecker'] = _WOODPECKER

# @@protoc_insertion_point(module_scope)
