# Generated by Django 4.1.1 on 2022-09-26 08:54

import cleverstack_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleverstack_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', cleverstack_auth.models.UserManager()),
            ],
        ),
    ]
