# Generated by Django 4.1.1 on 2022-09-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleverstack_auth', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'default_permissions': [], 'ordering': ['-created_at'], 'permissions': (('access_organisation', 'Access'), ('detail_organisation', 'View'), ('view_organisation', 'List'), ('change_organisation', 'Edit'), ('delete_organisation', 'Delete'), ('add_organisation', 'Create')), 'verbose_name': 'Organisation'},
        ),
    ]
