
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-29T16:26:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d86f5d11046791a2947ba45d594882020d6dab9",
 "version": "0.2.30.post0.dev26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
