info = {"message": "Merge branch 'ls-release/1.6.0' of github.com:heartexlabs/label-studio into ls-release/1.6.0", "commit": "d45c824dff845f027b187f4f585a2d1d978831c1", "date": "2022-09-27 15:34:33 +0100", "branch": "ls-release/1.6.0", "version": "1.4.1+566.gd45c824d"}

# This file is automatically generated by version.py
# Do not include it to git!
