from __future__ import annotations
from enum import Enum

__NAMESPACE__ = "http://www.energistics.org/energyml/data/prodmlv2"


class SulfurComponentKind(Enum):
    VALUE_2_3_2_4_DIMETHYL_THIOPHENE = "2-3 &amp; 2-4 dimethyl thiophene"
    VALUE_2_5_DIMETHYL_THIOPHENE = "2-5-dimethyl thiophene"
    VALUE_2_ETHYL_THIOPHENE = "2-ethyl thiophene"
    VALUE_2_METHYL_1_BUTANETHIOL = "2-methyl 1-butanethiol"
    VALUE_2_METHYL_THIPOPHENE = "2-methyl thipophene"
    VALUE_3_4_DIMETHYL_THIOPHENE = "3-4-dimethyl thiophene"
    VALUE_3_ETHYL_THIOPHENE = "3-ethyl thiophene"
    VALUE_3_METHYL_THIPOPHENE = "3-methyl thipophene"
    BENZOTHIOPHENE = "benzothiophene"
    CARBON_DISULFIDE = "carbon disulfide"
    CARBONYL_SULFIDE = "carbonyl sulfide"
    DIBUTYL_SULFIDE = "dibutyl sulfide"
    DIETHYL_DISULFIDE = "diethyl disulfide"
    DIETHYL_SULFIDE = "diethyl sulfide"
    DIMETHYL_DISULFIDE = "dimethyl disulfide"
    DIMETHYL_SULFIDE = "dimethyl sulfide"
    DIPROPYL_SULFIDE = "dipropyl sulfide"
    DI_SEC_BUTYL_SULFIDE = "di-sec.butyl sulfide"
    DITERT_BUTYL_SULFIDE = "ditert.butyl sulfide"
    ETHYL_ISOPROPYL_DISULFIDE = "ethyl isopropyl disulfide"
    ETHYL_MERCAPTAN = "ethyl mercaptan"
    ETHYL_METHYL_SULFIDE = "ethyl-methyl sulfide"
    HYDROGEN_SULFIDE = "hydrogen sulfide"
    ISOBUTYL_MERCAPTAN = "isobutyl mercaptan"
    ISOPENTYL_MERCAPTAN = "isopentyl mercaptan"
    ISOPROPYL_MERCAPTAN = "isopropyl mercaptan"
    METHYL_ISOPROPYL_SULFIDE = "methyl isopropyl sulfide"
    METHYL_MERCAPTAN = "methyl mercaptan"
    N_BUTYL_MERCAPTAN = "n-butyl mercaptan"
    N_HEPTYL_MERCAPTAN = "n-heptyl mercaptan"
    N_HEXYL_MERCAPTAN = "n-hexyl mercaptan"
    N_NONYL_MERCAPTAN = "n-nonyl mercaptan"
    N_OCTYL_MERCAPTAN = "n-octyl mercaptan"
    N_PENTYL_MERCAPTAN = "n-pentyl mercaptan"
    N_PROPYL_MERCAPTAN = "n-propyl mercaptan"
    SEC_BUTYL_MERCAPTAN = "sec-butyl mercaptan"
    TERT_BUTYL_MERCAPTAN = "tert-butyl mercaptan"
    TETRA_HYDRO_THIOPHENE = "tetra-hydro thiophene"
    THIOPHENE = "thiophene"
