VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('25')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 0
MINOR_VERSION = 14
PATCH_VERSION = 202209251100
version_date = '2022/09/25 11:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
