
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-28T20:12:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d5b816410bb1a5614dc77dd38db9975bdf07ece",
 "version": "1.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
