"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class error_types(_error_types, metaclass=_error_typesEnumTypeWrapper):
    pass
class _error_types:
    V = typing.NewType('V', builtins.int)
class _error_typesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_error_types.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ft_Error = error_types.V(0)
    ft_DeviceError = error_types.V(1)
    ft_ProtocolError = error_types.V(2)
    out_of_range = error_types.V(3)
    unknown_error = error_types.V(4)
    contention_timeout = error_types.V(5)
    ft_ServerError = error_types.V(6)
    ft_AuthError = error_types.V(7)

ft_Error = error_types.V(0)
ft_DeviceError = error_types.V(1)
ft_ProtocolError = error_types.V(2)
out_of_range = error_types.V(3)
unknown_error = error_types.V(4)
contention_timeout = error_types.V(5)
ft_ServerError = error_types.V(6)
ft_AuthError = error_types.V(7)
global___error_types = error_types


class errstatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TP_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    tp: global___error_types.V = ...
    msg: typing.Text = ...
    def __init__(self,
        *,
        tp : global___error_types.V = ...,
        msg : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"msg",b"msg",u"tp",b"tp"]) -> None: ...
global___errstatus = errstatus
