"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import ft_error_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class session_info(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERR_FIELD_NUMBER: builtins.int
    SESSIONID_FIELD_NUMBER: builtins.int
    USER_IDENTIFIER_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    DEVICES_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    EXPIRY_FIELD_NUMBER: builtins.int
    @property
    def err(self) -> ft_error_pb2.errstatus: ...
    sessionid: builtins.bytes = ...
    user_identifier: typing.Text = ...
    comment: typing.Text = ...
    @property
    def devices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def flags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def expiry(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        err : typing.Optional[ft_error_pb2.errstatus] = ...,
        sessionid : builtins.bytes = ...,
        user_identifier : typing.Text = ...,
        comment : typing.Text = ...,
        devices : typing.Optional[typing.Iterable[builtins.int]] = ...,
        flags : typing.Optional[typing.Iterable[typing.Text]] = ...,
        expiry : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"err",b"err",u"expiry",b"expiry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"comment",b"comment",u"devices",b"devices",u"err",b"err",u"expiry",b"expiry",u"flags",b"flags",u"sessionid",b"sessionid",u"user_identifier",b"user_identifier"]) -> None: ...
global___session_info = session_info

class session_list(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERR_FIELD_NUMBER: builtins.int
    SESSIONS_FIELD_NUMBER: builtins.int
    @property
    def err(self) -> ft_error_pb2.errstatus: ...
    @property
    def sessions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___session_info]: ...
    def __init__(self,
        *,
        err : typing.Optional[ft_error_pb2.errstatus] = ...,
        sessions : typing.Optional[typing.Iterable[global___session_info]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"err",b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"err",b"err",u"sessions",b"sessions"]) -> None: ...
global___session_list = session_list
