
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T04:36:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a7c5764a2e93f6d7a100299c7b39713c7b603ff",
 "version": "1.17.1.post0.dev134"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
