from __future__ import annotations
from enum import Enum

__NAMESPACE__ = "http://www.energistics.org/energyml/data/commonv2"


class AxisDirectionKind(Enum):
    """
    Direction of positive increase in the coordinate value for a coordinate
    system axis (from ISO 19111)
    """
    AFT = "aft"
    AWAY_FROM = "away-from"
    CLOCKWISE = "clockwise"
    COLUMN_NEGATIVE = "column-negative"
    COLUMN_POSITIVE = "column-positive"
    COUNTER_CLOCKWISE = "counter-clockwise"
    DISPLAY_DOWN = "display-down"
    DISPLAY_LEFT = "display-left"
    DISPLAY_RIGHT = "display-right"
    DISPLAY_UP = "display-up"
    DOWN = "down"
    EAST = "east"
    EAST_NORTH_EAST = "east-north-east"
    EAST_SOUTH_EAST = "east-south-east"
    FORWARD = "forward"
    FUTURE = "future"
    GEOCENTRIC_X = "geocentric x"
    GEOCENTRIC_Y = "geocentric y"
    GEOCENTRIC_Z = "geocentric z"
    NORTH = "north"
    NORTH_EAST = "north-east"
    NORTH_NORTH_EAST = "north-north-east"
    NORTH_NORTH_WEST = "north-north-west"
    NORTH_WEST = "north-west"
    PAST = "past"
    PORT = "port"
    ROW_NEGATIVE = "row-negative"
    ROW_POSITIVE = "row-positive"
    SOUTH = "south"
    SOUTH_EAST = "south-east"
    SOUTH_SOUTH_EAST = "south-south-east"
    SOUTH_SOUTH_WEST = "south-south-west"
    SOUTH_WEST = "south-west"
    STARBOARD = "starboard"
    TOWARDS = "towards"
    UP = "up"
    WEST = "west"
    WEST_NORTH_WEST = "west-north-west"
    WEST_SOUTH_WEST = "west-south-west"
