from __future__ import annotations
from enum import Enum

__NAMESPACE__ = "http://www.energistics.org/energyml/data/witsmlv2"


class Coating(Enum):
    """
    Specifies the values for the type of inside or outside coating of this
    piece of equipment.
    """
    BARE = "bare"
    CARBONNITRIDED = "carbonnitrided"
    CARBURIZED = "carburized"
    CARBURIZED_HARDENED = "carburized-hardened"
    CEMENTLINED = "cementlined"
    CHROME = "chrome"
    CHROME_PLATED = "chrome-plated"
    CHROMEPLATED_GROOVED = "chromeplated-grooved"
    CHROMEPLATED_HEAVY = "chromeplated-heavy"
    CORROSION_COATING = "corrosion coating"
    DBLGALV = "dblgalv"
    DUOLIN20WR = "duolin20wr"
    DUOLINE = "duoline"
    DUOLINE10 = "duoline10"
    DUOLINE20 = "duoline20"
    EPDM = "epdm"
    FIBERGLASS_LINED = "fiberglass-lined"
    GALVANIZED = "galvanized"
    HARDENED = "hardened"
    HARD_LINED = "hard-lined"
    INS = "ins"
    IPC = "ipc"
    IPC_EPOXY = "ipc-epoxy"
    IPC_EPXTHK = "ipc-epxthk"
    IPC_EPXTHN = "ipc-epxthn"
    IPC_NYLON = "ipc-nylon"
    IPC_RWRAP = "ipc-rwrap"
    IPC_S505 = "ipc-s505"
    IPC_S650 = "ipc-s650"
    IPC_TK70 = "ipc-tk70"
    IPC_TK75 = "ipc-tk75"
    LP = "lp"
    MOLY = "moly"
    MTR = "mtr"
    N_A = "n/a"
    NICKEL_CARBIDE = "nickel-carbide"
    NICKEL_PLATED = "nickel-plated"
    NITRIDED = "nitrided"
    NITRILE = "nitrile"
    PAP = "pap"
    PELINED = "pelined"
    PHOSPHATE = "phosphate"
    PHOSPHORUS = "phosphorus"
    PLASTIC = "plastic"
    PLUNGER_LUBRICANT = "plunger-lubricant"
    POLISHED_RODLINER = "polished-rodliner"
    POLYPROPYLENE = "polypropylene"
    PPW_NITRL = "ppw/nitrl"
    PVCLINED = "pvclined"
    RODGUIDE_1 = "rodguide-1"
    RODGUIDE_2 = "rodguide-2"
    RODGUIDE_2_1 = "rodguide-2."
    RODGUIDE_3 = "rodguide-3"
    RODGUIDE_4 = "rodguide-4"
    RODGUIDE_5 = "rodguide-5"
    RODGUIDE_6 = "rodguide-6"
    RODGUIDE_7 = "rodguide-7"
    RODGUIDE_FX = "rodguide-fx"
    RODGUIDE_SO = "rodguide-so"
    RODGUIDE_SO1 = "rodguide-so1"
    RODGUIDE_SO2 = "rodguide-so2"
    RODGUIDE_SO3 = "rodguide-so3"
    RODGUIDE_SO4 = "rodguide-so4"
    RODGUIDE_SO5 = "rodguide-so5"
    RODGUIDE_SO6 = "rodguide-so6"
    RODGUIDE_SO8 = "rodguide-so8"
    RODGUIDE_SP = "rodguide-sp"
    SPRAY_METAL = "spray-metal"
    SPRAY_METAL_MONEL = "spray-metal-monel"
    SPRAYMETAL_MONEL_1 = "spraymetal-monel"
    SPRAYMETAL_NICKEL = "spraymetal-nickel"
    SPRAYMETAL_OD_NICKELPLATED_ID = "spraymetal-od/nickelplated-id"
    SPRAYMETAL_STEEL = "spraymetal-steel"
    SPRAYMETAL_THICK = "spraymetal-thick"
    SSLINED = "sslined"
    TEFLON = "teflon"
    TEFLON_RED = "teflon-red"
    TEFLON_TAN = "teflon-tan"
    TEFLON_YELLOW = "teflon-yellow"
    THERMO = "thermo"
    TK_4 = "tk-4"
    TK_99 = "tk-99"
    TUFFR = "tuffr"
    TUNGSTEN_PLATED = "tungsten plated"
    ZINCPLATED = "zincplated"
