from __future__ import annotations
from enum import Enum

__NAMESPACE__ = "http://www.energistics.org/energyml/data/witsmlv2"


class MudSubType(Enum):
    """
    The name of a data extension.
    """
    AERATED_MUD = "aerated mud"
    AIR = "air"
    BRACKISH_WATER = "brackish water"
    BRINE = "brine"
    CAESIUM_FORMATE = "caesium formate"
    DIESEL_OIL_BASED = "diesel oil-based"
    ESTER_SYNTHETIC_BASED = "ester synthetic-based"
    FRESHWATER = "freshwater"
    GLYCOL_MUD = "glycol mud"
    GYP_MUD = "gyp mud"
    INTERNAL_OLEFIN_SYNTHETIC_BASED = "internal-olefin synthetic-based"
    LIGHTLY_TREATED_NON_DISPERSED = "lightly treated non-dispersed"
    LIGNITE_LIGNOSULFONATE_MUD = "lignite/lignosulfonate mud"
    LIME_MUD = "lime mud"
    LINEAR_PARAFFIN_SYNTHETIC_BASED = "linear paraffin synthetic-based"
    LINEAR_ALPHA_OLEFIN_SYNTHETIC_BASED = "linear-alpha-olefin synthetic-based"
    LOW_SOLIDS = "low solids"
    LOW_TOXICITY_MINERAL_OIL_BASED = "low toxicity mineral oil-based"
    MINERAL_OIL_BASED = "mineral oil-based"
    MIST = "mist"
    MIXED_METAL_OXIDE_MUD = "mixed-metal oxide mud"
    NATIVE_NATURAL_MUD = "native/natural mud"
    NATURAL_GAS = "natural gas"
    NITROGEN_AERATED_MUD = "nitrogen-aerated mud"
    NON_AQUEOUS_INVERT_EMULSION_DRILLING_FLUIDS = "non-aqueous (invert emulsion) drilling fluids"
    NON_DISPERSED = "non-dispersed"
    PNEUMATIC_GASEOUS_DRILLING_FLUIDS = "pneumatic (gaseous) drilling fluids"
    POLYMER_MUD = "polymer mud"
    POTASSIUM_FORMATE = "potassium formate"
    POTASSIUM_TREATED_MUD = "potassium-treated mud"
    SALT_WATER_MUD = "salt water mud"
    SATURATED_SALT_MUD = "saturated salt mud"
    SEA_WATER = "sea water"
    SEAWATER_MUD = "seawater mud"
    SILICATE_MUD = "silicate mud"
    SODIUM_FORMATE = "sodium formate"
    SPUD_MUD = "spud mud"
    STABLE_FOAM = "stable foam"
    STIFF_FOAM = "stiff foam"
    WATER_BASED_DRILLING_FLUIDS = "water-based drilling fluids"
