"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import th2_grpc_common.common_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Side:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _SideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Side.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SIDE_UNSPECIFIED: _Side.ValueType  # 0
    SIDE_BUY: _Side.ValueType  # 1
    SIDE_SELL: _Side.ValueType  # 2
class Side(_Side, metaclass=_SideEnumTypeWrapper):
    pass

SIDE_UNSPECIFIED: Side.ValueType  # 0
SIDE_BUY: Side.ValueType  # 1
SIDE_SELL: Side.ValueType  # 2
global___Side = Side


class PlaceOrderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONNECTION_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    ORD_TYPE_FIELD_NUMBER: builtins.int
    ORDER_QTY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    CL_ORD_ID_FIELD_NUMBER: builtins.int
    TIME_IN_FORCE_FIELD_NUMBER: builtins.int
    TRADING_PARTY_FIELD_NUMBER: builtins.int
    @property
    def connection(self) -> th2_grpc_common.common_pb2.ConnectionID: ...
    symbol: typing.Text
    ord_type: typing.Text
    order_qty: builtins.float
    """might be a problem with some values..."""

    price: builtins.float
    """might be a problem with some values..."""

    side: global___Side.ValueType
    cl_ord_id: typing.Text
    """optional, will be generated automatically"""

    time_in_force: typing.Text
    """optional, will be 0 by default"""

    @property
    def trading_party(self) -> global___TradingParty:
        """optional, will be taken from act config by session alias"""
        pass
    def __init__(self,
        *,
        connection: typing.Optional[th2_grpc_common.common_pb2.ConnectionID] = ...,
        symbol: typing.Text = ...,
        ord_type: typing.Text = ...,
        order_qty: builtins.float = ...,
        price: builtins.float = ...,
        side: global___Side.ValueType = ...,
        cl_ord_id: typing.Optional[typing.Text] = ...,
        time_in_force: typing.Optional[typing.Text] = ...,
        trading_party: typing.Optional[global___TradingParty] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_cl_ord_id",b"_cl_ord_id","_time_in_force",b"_time_in_force","cl_ord_id",b"cl_ord_id","connection",b"connection","time_in_force",b"time_in_force","trading_party",b"trading_party"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_cl_ord_id",b"_cl_ord_id","_time_in_force",b"_time_in_force","cl_ord_id",b"cl_ord_id","connection",b"connection","ord_type",b"ord_type","order_qty",b"order_qty","price",b"price","side",b"side","symbol",b"symbol","time_in_force",b"time_in_force","trading_party",b"trading_party"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_cl_ord_id",b"_cl_ord_id"]) -> typing.Optional[typing_extensions.Literal["cl_ord_id"]]: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_time_in_force",b"_time_in_force"]) -> typing.Optional[typing_extensions.Literal["time_in_force"]]: ...
global___PlaceOrderRequest = PlaceOrderRequest

class TradingParty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    id: typing.Text
    source: typing.Text
    role: builtins.int
    def __init__(self,
        *,
        id: typing.Text = ...,
        source: typing.Text = ...,
        role: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","role",b"role","source",b"source"]) -> None: ...
global___TradingParty = TradingParty

class PlaceOrderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHECKPOINT_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def checkpoint(self) -> th2_grpc_common.common_pb2.Checkpoint: ...
    @property
    def response(self) -> th2_grpc_common.common_pb2.Message: ...
    def __init__(self,
        *,
        checkpoint: typing.Optional[th2_grpc_common.common_pb2.Checkpoint] = ...,
        response: typing.Optional[th2_grpc_common.common_pb2.Message] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["checkpoint",b"checkpoint","response",b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["checkpoint",b"checkpoint","response",b"response"]) -> None: ...
global___PlaceOrderResponse = PlaceOrderResponse
