# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.3.dev279+g3725d4c2.d20220928'
__version_tuple__ = version_tuple = (1, 0, 3, 'dev279', 'g3725d4c2.d20220928')
