
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-29T11:38:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "991f2a2c99cf07ded4fe1b75765956f5c85c7795",
 "version": "0.2.30.post0.dev27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
