# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\x12\rmessagev.base\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x03\n\x08\x45nvelope\x12\x15\n\rmajor_version\x18\x01 \x01(\r\x12\x15\n\rminor_version\x18\x02 \x01(\r\x12\x12\n\nmessage_id\x18\x03 \x01(\x0c\x12\x13\n\x0bresponse_to\x18\x04 \x01(\x0c\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0esender_node_id\x18\x06 \x01(\t\x12\x18\n\x10receiver_node_id\x18\x07 \x01(\t\x12\x12\n\nmodel_name\x18\x08 \x01(\t\x12\x0e\n\x06res_id\x18\t \x01(\x04\x12\x38\n\x0cmessage_type\x18\n \x01(\x0e\x32\".messagev.base.Envelope.TypeOption\x12\x14\n\x0cmessage_body\x18\x0b \x01(\x0c\"\\\n\nTypeOption\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43OMMAND\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\x0b\n\x07REQUEST\x10\x03\x12\x10\n\x0cNOTIFICATION\x10\x04\x12\x07\n\x03LOG\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENVELOPE._serialized_start=63
  _ENVELOPE._serialized_end=467
  _ENVELOPE_TYPEOPTION._serialized_start=375
  _ENVELOPE_TYPEOPTION._serialized_end=467
# @@protoc_insertion_point(module_scope)
