
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T10:38:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "60ca8f280e5e89112297869adf2cdb173e3636b1",
 "version": "v22.12.00a220928"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
