VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('26')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('47')
MAJOR_VERSION = 0
MINOR_VERSION = 14
PATCH_VERSION = 202209261447
version_date = '2022/09/26 14:47'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
