
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-28T18:13:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "95bdc0d90fec2e9d5667af2913a61727f26e1f3a",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
