
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-29T15:33:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "894950aa307ca5ed6ea038a49ef6229360ac6120",
 "version": "2772"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
