
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-29T06:13:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "25eec79c922da4cbc05d3056c259dd8625e4ab1d",
 "version": "1.17.1.post0.dev176"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
