
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T14:20:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aee3cb1d9cc52293a1865d49b6e8be21480ff2ae",
 "version": "0.post0.dev24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
