# Generated by Django 4.0.4 on 2022-04-22 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=functools.partial(secrets.token_urlsafe, *(128,), **{}), max_length=171)),
                ('created', models.DateTimeField(auto_now=True)),
                ('expires_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
