
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-25T02:58:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbf128b09a5b21cb5ca023ae955e2a038f92f9b2",
 "version": "0.4.dev2239"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
