VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('27')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('12')
MAJOR_VERSION = 0
MINOR_VERSION = 14
PATCH_VERSION = 202209271612
version_date = '2022/09/27 16:12'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
