
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-28T14:53:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad132d258ae75f8afb39b9817d608d740542544b",
 "version": "2022.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
