
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-29T23:34:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc19b64831b9473daae3d9b1878df5d6c75af308",
 "version": "0.1.0-beta"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
