from aioworkers.core.formatter import FormattedEntity
from aioworkers.storage.base import AbstractStorage
from aioworkers_boto.core import Connector as Connector
from typing import Any

class Storage(AbstractStorage, FormattedEntity, Connector):
    def __init__(self, *args, **kwargs) -> None: ...
    def set_config(self, config) -> None: ...
    def raw_key(self, key: str) -> str: ...
    async def get(self, key: str, *, bucket: str = ...) -> Any: ...
    async def set(self, key: str, value: Any, *, bucket: str = ...): ...
