
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-30T16:52:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3579e4c30a59e444ecfc67dcc55616d8bbd1cd9e",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
