
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-30T09:05:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b4be0ac08a28b30e89d0e68742d94b3947df0c1",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
