# Generated by Django 4.0.4 on 2022-04-22 10:54

from django.db import migrations, models
import functools
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('drf_temptoken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptoken',
            name='key',
            field=models.CharField(blank=True, db_index=True, default=functools.partial(secrets.token_urlsafe, *(128,), **{}), max_length=171),
        ),
    ]
