'''__init__.py'''


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._956 import AddendumModificationDistributionRule
    from ._957 import BacklashSpecification
    from ._958 import BasicRackProfiles
    from ._959 import CaseHardeningProperties
    from ._960 import CreateNewSuitableCutterOption
    from ._961 import CrossedAxisCylindricalGearPair
    from ._962 import CrossedAxisCylindricalGearPairLineContact
    from ._963 import CrossedAxisCylindricalGearPairPointContact
    from ._964 import CylindricalGearAbstractRack
    from ._965 import CylindricalGearAbstractRackFlank
    from ._966 import CylindricalGearBasicRack
    from ._967 import CylindricalGearBasicRackFlank
    from ._968 import CylindricalGearCuttingOptions
    from ._969 import CylindricalGearDefaults
    from ._970 import CylindricalGearDesign
    from ._971 import CylindricalGearDesignConstraint
    from ._972 import CylindricalGearDesignConstraints
    from ._973 import CylindricalGearDesignConstraintsDatabase
    from ._974 import CylindricalGearDesignConstraintSettings
    from ._975 import CylindricalGearDesignSettings
    from ._976 import CylindricalGearFlankDesign
    from ._977 import CylindricalGearMeshDesign
    from ._978 import CylindricalGearMeshFlankDesign
    from ._979 import CylindricalGearMicroGeometrySettings
    from ._980 import CylindricalGearPinionTypeCutter
    from ._981 import CylindricalGearPinionTypeCutterFlank
    from ._982 import CylindricalGearProfileMeasurement
    from ._983 import CylindricalGearProfileMeasurementType
    from ._984 import CylindricalGearProfileModifications
    from ._985 import CylindricalGearSetDesign
    from ._986 import CylindricalGearSetFlankDesign
    from ._987 import CylindricalGearSetMacroGeometryOptimiser
    from ._988 import CylindricalGearSetManufacturingConfigurationSelection
    from ._989 import CylindricalGearTableMGItemDetail
    from ._990 import CylindricalGearTableWithMGCharts
    from ._991 import CylindricalGearToothThicknessSpecification
    from ._992 import CylindricalMeshAngularBacklash
    from ._993 import CylindricalMeshedGear
    from ._994 import CylindricalMeshedGearFlank
    from ._995 import CylindricalMeshLinearBacklashSpecification
    from ._996 import CylindricalPlanetaryGearSetDesign
    from ._997 import CylindricalPlanetGearDesign
    from ._998 import DIN3967AllowanceSeries
    from ._999 import DIN3967ToleranceSeries
    from ._1000 import DoubleAxisScaleAndRange
    from ._1001 import FinishStockSpecification
    from ._1002 import FinishToothThicknessDesignSpecification
    from ._1003 import GearFitSystems
    from ._1004 import GearManufacturingConfigSetupViewModel
    from ._1005 import GearSetManufacturingConfigurationSetup
    from ._1006 import GeometrySpecificationType
    from ._1007 import HardenedMaterialProperties
    from ._1008 import HardnessProfileCalculationMethod
    from ._1009 import HeatTreatmentType
    from ._1010 import ISO6336Geometry
    from ._1011 import ISO6336GeometryBase
    from ._1012 import ISO6336GeometryForShapedGears
    from ._1013 import ISO6336GeometryManufactured
    from ._1014 import LinearBacklashSepcification
    from ._1015 import LTCALoadCaseModifiableSettings
    from ._1016 import LtcaSettings
    from ._1017 import MicroGeometryConvention
    from ._1018 import MicroGeometryProfileConvention
    from ._1019 import Micropitting
    from ._1020 import NamedPlanetAssemblyIndex
    from ._1021 import NamedPlanetSideBandAmplitudeFactor
    from ._1022 import ReadonlyToothThicknessSpecification
    from ._1023 import RelativeMeasurementViewModel
    from ._1024 import RelativeValuesSpecification
    from ._1025 import RootStressSurfaceChartOption
    from ._1026 import Scuffing
    from ._1027 import ScuffingCoefficientOfFrictionMethods
    from ._1028 import ScuffingTemperatureMethodsAGMA
    from ._1029 import ScuffingTemperatureMethodsISO
    from ._1030 import ShaperEdgeTypes
    from ._1031 import SpurGearLoadSharingCodes
    from ._1032 import StandardRack
    from ._1033 import StandardRackFlank
    from ._1034 import SurfaceRoughness
    from ._1035 import ThicknessType
    from ._1036 import TiffAnalysisSettings
    from ._1037 import TipAlterationCoefficientMethod
    from ._1038 import TolerancedMetalMeasurements
    from ._1039 import TolerancedValueSpecification
    from ._1040 import ToothFlankFractureAnalysisSettings
    from ._1041 import ToothThicknessSpecification
    from ._1042 import ToothThicknessSpecificationBase
    from ._1043 import TypeOfMechanismHousing
    from ._1044 import Usage
