
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-29T04:05:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "75d464e505a0ab5d99f5c06b5e3763406158e232",
 "version": "1.17.1.post0.dev162"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
