
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-21T17:20:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d02682fb7a348a30cfa10f6bbf8deda5e7fa9310",
 "version": "0.0.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
