
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T20:19:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbdb01a7cdfa7b25e029c6945ca7ff3c3a3409fd",
 "version": "0.2.30.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
