
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "27a576e352a9b3d9abee89ab92cd02012c0e39dd",
 "version": "1.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
