
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-28T17:04:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad5f4b89ec633843628b7c5d2f58ba5e9c15e29b",
 "version": "0.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
