from typing import Any, Generator

from .declarative import MetaEntity

class Entity(metaclass=MetaEntity):
    @classmethod
    @property
    def __tablename__(cls) -> str: ...
    @classmethod
    def _fields(cls) -> Generator[str, None, None]: ...
    def __iter__(self) -> Generator[tuple[str, Any], None, None]: ...
    def dict(self) -> dict[str, Any]: ...
    def set(self, **vals) -> None: ...
