# Generated by Django 4.1.1 on 2022-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_biller_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
