from baseblock import BaseObject
from typing import Dict, List

class ModelConfigLoader(BaseObject):
    def __init__(self) -> None: ...
    def by_name(self, model_name: str) -> Dict: ...
    def all(self) -> List: ...
