
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-26T12:28:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "801747389cb63a1db1f94aec5ae190f13a3b5d5b",
 "version": "2770"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
