
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-28T16:21:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "869201155dcc9b4c8fbe72d99310c7e8e53d4c54",
 "version": "1.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
