from baseblock import BaseObject
from speech_patho_mdl.dto import ServiceEvent as ServiceEvent
from typing import Callable, Optional

class ModelAPI(BaseObject):
    def __init__(self) -> None: ...
    def classify(self, input: list) -> ServiceEvent: ...
    def initialize(self, classification: str) -> Optional[Callable]: ...
    def invoke(self, model: Callable, input_text: Optional[str], source_user: Optional[str], target_user: Optional[str]) -> ServiceEvent: ...
