VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('29')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 0
MINOR_VERSION = 10
PATCH_VERSION = 202209291111
version_date = '2022/09/29 11:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
