from aiobotocore.client import AioBaseClient as AioBaseClient
from aiobotocore.session import ClientCreatorContext as ClientCreatorContext
from aioworkers.core.base import AbstractConnector

class Connector(AbstractConnector):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def client(self) -> AioBaseClient: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def __aenter__(self) -> None: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
