
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-25T11:22:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4bc22ad54e4fdc4a87b520e6359478897943a62",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
