
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T19:08:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f31846deb1a61acf4f576d0230b9dcc89df5d84d",
 "version": "0.2.30.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
