# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: annotations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61nnotations.proto\x1a google/protobuf/descriptor.proto*|\n\tAuthLevel\x12\x16\n\x12\x41UTH_LEVEL_UNKNOWN\x10\x00\x12\x13\n\x0f\x41UTH_LEVEL_OPEN\x10\x01\x12\x15\n\x11\x41UTH_LEVEL_JAILED\x10\x02\x12\x15\n\x11\x41UTH_LEVEL_SECURE\x10\x03\x12\x14\n\x10\x41UTH_LEVEL_ADMIN\x10\x04:2\n\tsensitive\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x08:A\n\nauth_level\x12\x1f.google.protobuf.ServiceOptions\x18\xd1\x86\x03 \x01(\x0e\x32\n.AuthLevelb\x06proto3')

_AUTHLEVEL = DESCRIPTOR.enum_types_by_name['AuthLevel']
AuthLevel = enum_type_wrapper.EnumTypeWrapper(_AUTHLEVEL)
AUTH_LEVEL_UNKNOWN = 0
AUTH_LEVEL_OPEN = 1
AUTH_LEVEL_JAILED = 2
AUTH_LEVEL_SECURE = 3
AUTH_LEVEL_ADMIN = 4

SENSITIVE_FIELD_NUMBER = 50000
sensitive = DESCRIPTOR.extensions_by_name['sensitive']
AUTH_LEVEL_FIELD_NUMBER = 50001
auth_level = DESCRIPTOR.extensions_by_name['auth_level']

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(sensitive)
  google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(auth_level)

  DESCRIPTOR._options = None
  _AUTHLEVEL._serialized_start=55
  _AUTHLEVEL._serialized_end=179
# @@protoc_insertion_point(module_scope)
