# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import annotations_pb2 as annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\x1aorg.couchers.notifications\x1a\x11\x61nnotations.proto\"\x1c\n\x1aGetNotificationSettingsReq\"?\n\x1aGetNotificationSettingsRes\x12!\n\x19new_notifications_enabled\x18\x01 \x01(\x08\">\n\x1aSetNotificationSettingsReq\x12 \n\x18\x65nable_new_notifications\x18\x01 \x01(\x08\"\x1c\n\x1aSetNotificationSettingsRes2\xad\x02\n\rNotifications\x12\x89\x01\n\x17GetNotificationSettings\x12\x36.org.couchers.notifications.GetNotificationSettingsReq\x1a\x36.org.couchers.notifications.GetNotificationSettingsRes\x12\x89\x01\n\x17SetNotificationSettings\x12\x36.org.couchers.notifications.SetNotificationSettingsReq\x1a\x36.org.couchers.notifications.SetNotificationSettingsRes\x1a\x04\x88\xb5\x18\x03\x62\x06proto3')



_GETNOTIFICATIONSETTINGSREQ = DESCRIPTOR.message_types_by_name['GetNotificationSettingsReq']
_GETNOTIFICATIONSETTINGSRES = DESCRIPTOR.message_types_by_name['GetNotificationSettingsRes']
_SETNOTIFICATIONSETTINGSREQ = DESCRIPTOR.message_types_by_name['SetNotificationSettingsReq']
_SETNOTIFICATIONSETTINGSRES = DESCRIPTOR.message_types_by_name['SetNotificationSettingsRes']
GetNotificationSettingsReq = _reflection.GeneratedProtocolMessageType('GetNotificationSettingsReq', (_message.Message,), {
  'DESCRIPTOR' : _GETNOTIFICATIONSETTINGSREQ,
  '__module__' : 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:org.couchers.notifications.GetNotificationSettingsReq)
  })
_sym_db.RegisterMessage(GetNotificationSettingsReq)

GetNotificationSettingsRes = _reflection.GeneratedProtocolMessageType('GetNotificationSettingsRes', (_message.Message,), {
  'DESCRIPTOR' : _GETNOTIFICATIONSETTINGSRES,
  '__module__' : 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:org.couchers.notifications.GetNotificationSettingsRes)
  })
_sym_db.RegisterMessage(GetNotificationSettingsRes)

SetNotificationSettingsReq = _reflection.GeneratedProtocolMessageType('SetNotificationSettingsReq', (_message.Message,), {
  'DESCRIPTOR' : _SETNOTIFICATIONSETTINGSREQ,
  '__module__' : 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:org.couchers.notifications.SetNotificationSettingsReq)
  })
_sym_db.RegisterMessage(SetNotificationSettingsReq)

SetNotificationSettingsRes = _reflection.GeneratedProtocolMessageType('SetNotificationSettingsRes', (_message.Message,), {
  'DESCRIPTOR' : _SETNOTIFICATIONSETTINGSRES,
  '__module__' : 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:org.couchers.notifications.SetNotificationSettingsRes)
  })
_sym_db.RegisterMessage(SetNotificationSettingsRes)

_NOTIFICATIONS = DESCRIPTOR.services_by_name['Notifications']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTIFICATIONS._options = None
  _NOTIFICATIONS._serialized_options = b'\210\265\030\003'
  _GETNOTIFICATIONSETTINGSREQ._serialized_start=70
  _GETNOTIFICATIONSETTINGSREQ._serialized_end=98
  _GETNOTIFICATIONSETTINGSRES._serialized_start=100
  _GETNOTIFICATIONSETTINGSRES._serialized_end=163
  _SETNOTIFICATIONSETTINGSREQ._serialized_start=165
  _SETNOTIFICATIONSETTINGSREQ._serialized_end=227
  _SETNOTIFICATIONSETTINGSRES._serialized_start=229
  _SETNOTIFICATIONSETTINGSRES._serialized_end=257
  _NOTIFICATIONS._serialized_start=260
  _NOTIFICATIONS._serialized_end=561
# @@protoc_insertion_point(module_scope)
