VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('27')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('44')
MAJOR_VERSION = 0
MINOR_VERSION = 14
PATCH_VERSION = 202209271844
version_date = '2022/09/27 18:44'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
