
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T17:52:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a6472a650fe2d2f719d64d5b94e070e69a1a66d",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
