
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T03:53:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5453fc570735463a2e147922455abd1068e86bd6",
 "version": "1.17.1.post0.dev128"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
