'''__init__.py'''


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._955 import AddendumModificationDistributionRule
    from ._956 import BacklashSpecification
    from ._957 import BasicRackProfiles
    from ._958 import CaseHardeningProperties
    from ._959 import CreateNewSuitableCutterOption
    from ._960 import CrossedAxisCylindricalGearPair
    from ._961 import CrossedAxisCylindricalGearPairLineContact
    from ._962 import CrossedAxisCylindricalGearPairPointContact
    from ._963 import CylindricalGearAbstractRack
    from ._964 import CylindricalGearAbstractRackFlank
    from ._965 import CylindricalGearBasicRack
    from ._966 import CylindricalGearBasicRackFlank
    from ._967 import CylindricalGearCuttingOptions
    from ._968 import CylindricalGearDefaults
    from ._969 import CylindricalGearDesign
    from ._970 import CylindricalGearDesignConstraint
    from ._971 import CylindricalGearDesignConstraints
    from ._972 import CylindricalGearDesignConstraintsDatabase
    from ._973 import CylindricalGearDesignConstraintSettings
    from ._974 import CylindricalGearDesignSettings
    from ._975 import CylindricalGearFlankDesign
    from ._976 import CylindricalGearMeshDesign
    from ._977 import CylindricalGearMeshFlankDesign
    from ._978 import CylindricalGearMicroGeometrySettings
    from ._979 import CylindricalGearPinionTypeCutter
    from ._980 import CylindricalGearPinionTypeCutterFlank
    from ._981 import CylindricalGearProfileMeasurement
    from ._982 import CylindricalGearProfileMeasurementType
    from ._983 import CylindricalGearProfileModifications
    from ._984 import CylindricalGearSetDesign
    from ._985 import CylindricalGearSetFlankDesign
    from ._986 import CylindricalGearSetMacroGeometryOptimiser
    from ._987 import CylindricalGearSetManufacturingConfigurationSelection
    from ._988 import CylindricalGearTableMGItemDetail
    from ._989 import CylindricalGearTableWithMGCharts
    from ._990 import CylindricalGearToothThicknessSpecification
    from ._991 import CylindricalMeshAngularBacklash
    from ._992 import CylindricalMeshedGear
    from ._993 import CylindricalMeshedGearFlank
    from ._994 import CylindricalMeshLinearBacklashSpecification
    from ._995 import CylindricalPlanetaryGearSetDesign
    from ._996 import CylindricalPlanetGearDesign
    from ._997 import DIN3967AllowanceSeries
    from ._998 import DIN3967ToleranceSeries
    from ._999 import DoubleAxisScaleAndRange
    from ._1000 import FinishStockSpecification
    from ._1001 import FinishToothThicknessDesignSpecification
    from ._1002 import GearFitSystems
    from ._1003 import GearManufacturingConfigSetupViewModel
    from ._1004 import GearSetManufacturingConfigurationSetup
    from ._1005 import GeometrySpecificationType
    from ._1006 import HardenedMaterialProperties
    from ._1007 import HardnessProfileCalculationMethod
    from ._1008 import HeatTreatmentType
    from ._1009 import ISO6336Geometry
    from ._1010 import ISO6336GeometryBase
    from ._1011 import ISO6336GeometryForShapedGears
    from ._1012 import ISO6336GeometryManufactured
    from ._1013 import LinearBacklashSepcification
    from ._1014 import LTCALoadCaseModifiableSettings
    from ._1015 import LtcaSettings
    from ._1016 import MicroGeometryConvention
    from ._1017 import MicroGeometryProfileConvention
    from ._1018 import Micropitting
    from ._1019 import NamedPlanetAssemblyIndex
    from ._1020 import NamedPlanetSideBandAmplitudeFactor
    from ._1021 import ReadonlyToothThicknessSpecification
    from ._1022 import RelativeMeasurementViewModel
    from ._1023 import RelativeValuesSpecification
    from ._1024 import Scuffing
    from ._1025 import ScuffingCoefficientOfFrictionMethods
    from ._1026 import ScuffingTemperatureMethodsAGMA
    from ._1027 import ScuffingTemperatureMethodsISO
    from ._1028 import ShaperEdgeTypes
    from ._1029 import SpurGearLoadSharingCodes
    from ._1030 import StandardRack
    from ._1031 import StandardRackFlank
    from ._1032 import SurfaceRoughness
    from ._1033 import ThicknessType
    from ._1034 import TiffAnalysisSettings
    from ._1035 import TipAlterationCoefficientMethod
    from ._1036 import TolerancedMetalMeasurements
    from ._1037 import TolerancedValueSpecification
    from ._1038 import ToothFlankFractureAnalysisSettings
    from ._1039 import ToothThicknessSpecification
    from ._1040 import ToothThicknessSpecificationBase
    from ._1041 import TypeOfMechanismHousing
    from ._1042 import Usage
