VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('26')
VERSION_HOUR = int('04')
VERSION_MINUTE = int('43')
MAJOR_VERSION = 0
MINOR_VERSION = 14
PATCH_VERSION = 202209260443
version_date = '2022/09/26 04:43'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
