
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T17:42:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b32f241c566a3a8264730694329ee6e2d6186c48",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
