
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T05:17:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e8bc5e7a708eaea35c240fb368736e96102d3f9",
 "version": "1.17.1.post0.dev140"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
