# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BatchNumberCounter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'counter': 'int',
        'crop_id': 'int',
        'crop_name': 'str',
        'crop_nick_name': 'str',
        'grade': 'str',
        'id': 'int',
        'plan_type_name': 'str',
        'variety_id': 'int',
        'variety_name': 'str',
        'variety_nick_name': 'str'
    }

    attribute_map = {
        'counter': 'counter',
        'crop_id': 'cropId',
        'crop_name': 'cropName',
        'crop_nick_name': 'cropNickName',
        'grade': 'grade',
        'id': 'id',
        'plan_type_name': 'planTypeName',
        'variety_id': 'varietyId',
        'variety_name': 'varietyName',
        'variety_nick_name': 'varietyNickName'
    }

    def __init__(self, counter=None, crop_id=None, crop_name=None, crop_nick_name=None, grade=None, id=None, plan_type_name=None, variety_id=None, variety_name=None, variety_nick_name=None):  # noqa: E501
        """BatchNumberCounter - a model defined in Swagger"""  # noqa: E501
        self._counter = None
        self._crop_id = None
        self._crop_name = None
        self._crop_nick_name = None
        self._grade = None
        self._id = None
        self._plan_type_name = None
        self._variety_id = None
        self._variety_name = None
        self._variety_nick_name = None
        self.discriminator = None
        if counter is not None:
            self.counter = counter
        if crop_id is not None:
            self.crop_id = crop_id
        if crop_name is not None:
            self.crop_name = crop_name
        if crop_nick_name is not None:
            self.crop_nick_name = crop_nick_name
        if grade is not None:
            self.grade = grade
        if id is not None:
            self.id = id
        if plan_type_name is not None:
            self.plan_type_name = plan_type_name
        if variety_id is not None:
            self.variety_id = variety_id
        if variety_name is not None:
            self.variety_name = variety_name
        if variety_nick_name is not None:
            self.variety_nick_name = variety_nick_name

    @property
    def counter(self):
        """Gets the counter of this BatchNumberCounter.  # noqa: E501


        :return: The counter of this BatchNumberCounter.  # noqa: E501
        :rtype: int
        """
        return self._counter

    @counter.setter
    def counter(self, counter):
        """Sets the counter of this BatchNumberCounter.


        :param counter: The counter of this BatchNumberCounter.  # noqa: E501
        :type: int
        """

        self._counter = counter

    @property
    def crop_id(self):
        """Gets the crop_id of this BatchNumberCounter.  # noqa: E501


        :return: The crop_id of this BatchNumberCounter.  # noqa: E501
        :rtype: int
        """
        return self._crop_id

    @crop_id.setter
    def crop_id(self, crop_id):
        """Sets the crop_id of this BatchNumberCounter.


        :param crop_id: The crop_id of this BatchNumberCounter.  # noqa: E501
        :type: int
        """

        self._crop_id = crop_id

    @property
    def crop_name(self):
        """Gets the crop_name of this BatchNumberCounter.  # noqa: E501


        :return: The crop_name of this BatchNumberCounter.  # noqa: E501
        :rtype: str
        """
        return self._crop_name

    @crop_name.setter
    def crop_name(self, crop_name):
        """Sets the crop_name of this BatchNumberCounter.


        :param crop_name: The crop_name of this BatchNumberCounter.  # noqa: E501
        :type: str
        """

        self._crop_name = crop_name

    @property
    def crop_nick_name(self):
        """Gets the crop_nick_name of this BatchNumberCounter.  # noqa: E501


        :return: The crop_nick_name of this BatchNumberCounter.  # noqa: E501
        :rtype: str
        """
        return self._crop_nick_name

    @crop_nick_name.setter
    def crop_nick_name(self, crop_nick_name):
        """Sets the crop_nick_name of this BatchNumberCounter.


        :param crop_nick_name: The crop_nick_name of this BatchNumberCounter.  # noqa: E501
        :type: str
        """

        self._crop_nick_name = crop_nick_name

    @property
    def grade(self):
        """Gets the grade of this BatchNumberCounter.  # noqa: E501


        :return: The grade of this BatchNumberCounter.  # noqa: E501
        :rtype: str
        """
        return self._grade

    @grade.setter
    def grade(self, grade):
        """Sets the grade of this BatchNumberCounter.


        :param grade: The grade of this BatchNumberCounter.  # noqa: E501
        :type: str
        """

        self._grade = grade

    @property
    def id(self):
        """Gets the id of this BatchNumberCounter.  # noqa: E501


        :return: The id of this BatchNumberCounter.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BatchNumberCounter.


        :param id: The id of this BatchNumberCounter.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def plan_type_name(self):
        """Gets the plan_type_name of this BatchNumberCounter.  # noqa: E501


        :return: The plan_type_name of this BatchNumberCounter.  # noqa: E501
        :rtype: str
        """
        return self._plan_type_name

    @plan_type_name.setter
    def plan_type_name(self, plan_type_name):
        """Sets the plan_type_name of this BatchNumberCounter.


        :param plan_type_name: The plan_type_name of this BatchNumberCounter.  # noqa: E501
        :type: str
        """

        self._plan_type_name = plan_type_name

    @property
    def variety_id(self):
        """Gets the variety_id of this BatchNumberCounter.  # noqa: E501


        :return: The variety_id of this BatchNumberCounter.  # noqa: E501
        :rtype: int
        """
        return self._variety_id

    @variety_id.setter
    def variety_id(self, variety_id):
        """Sets the variety_id of this BatchNumberCounter.


        :param variety_id: The variety_id of this BatchNumberCounter.  # noqa: E501
        :type: int
        """

        self._variety_id = variety_id

    @property
    def variety_name(self):
        """Gets the variety_name of this BatchNumberCounter.  # noqa: E501


        :return: The variety_name of this BatchNumberCounter.  # noqa: E501
        :rtype: str
        """
        return self._variety_name

    @variety_name.setter
    def variety_name(self, variety_name):
        """Sets the variety_name of this BatchNumberCounter.


        :param variety_name: The variety_name of this BatchNumberCounter.  # noqa: E501
        :type: str
        """

        self._variety_name = variety_name

    @property
    def variety_nick_name(self):
        """Gets the variety_nick_name of this BatchNumberCounter.  # noqa: E501


        :return: The variety_nick_name of this BatchNumberCounter.  # noqa: E501
        :rtype: str
        """
        return self._variety_nick_name

    @variety_nick_name.setter
    def variety_nick_name(self, variety_nick_name):
        """Sets the variety_nick_name of this BatchNumberCounter.


        :param variety_nick_name: The variety_nick_name of this BatchNumberCounter.  # noqa: E501
        :type: str
        """

        self._variety_nick_name = variety_nick_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchNumberCounter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchNumberCounter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
