# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BatchDetailsReportResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'batch_details_report_dtos': 'list[BatchDetailsReportDto]',
        'error_messages': 'list[str]'
    }

    attribute_map = {
        'batch_details_report_dtos': 'batchDetailsReportDtos',
        'error_messages': 'errorMessages'
    }

    def __init__(self, batch_details_report_dtos=None, error_messages=None):  # noqa: E501
        """BatchDetailsReportResponse - a model defined in Swagger"""  # noqa: E501
        self._batch_details_report_dtos = None
        self._error_messages = None
        self.discriminator = None
        if batch_details_report_dtos is not None:
            self.batch_details_report_dtos = batch_details_report_dtos
        if error_messages is not None:
            self.error_messages = error_messages

    @property
    def batch_details_report_dtos(self):
        """Gets the batch_details_report_dtos of this BatchDetailsReportResponse.  # noqa: E501


        :return: The batch_details_report_dtos of this BatchDetailsReportResponse.  # noqa: E501
        :rtype: list[BatchDetailsReportDto]
        """
        return self._batch_details_report_dtos

    @batch_details_report_dtos.setter
    def batch_details_report_dtos(self, batch_details_report_dtos):
        """Sets the batch_details_report_dtos of this BatchDetailsReportResponse.


        :param batch_details_report_dtos: The batch_details_report_dtos of this BatchDetailsReportResponse.  # noqa: E501
        :type: list[BatchDetailsReportDto]
        """

        self._batch_details_report_dtos = batch_details_report_dtos

    @property
    def error_messages(self):
        """Gets the error_messages of this BatchDetailsReportResponse.  # noqa: E501


        :return: The error_messages of this BatchDetailsReportResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._error_messages

    @error_messages.setter
    def error_messages(self, error_messages):
        """Sets the error_messages of this BatchDetailsReportResponse.


        :param error_messages: The error_messages of this BatchDetailsReportResponse.  # noqa: E501
        :type: list[str]
        """

        self._error_messages = error_messages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchDetailsReportResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchDetailsReportResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
