# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HarvestLossPercentageDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crop_id': 'int',
        'crop_name': 'str',
        'loss_in_quantity': 'float',
        'loss_percentage': 'float',
        'total_weight': 'float',
        'variety_id': 'int',
        'variety_name': 'str',
        'variety_unit': 'str'
    }

    attribute_map = {
        'crop_id': 'cropId',
        'crop_name': 'cropName',
        'loss_in_quantity': 'lossInQuantity',
        'loss_percentage': 'lossPercentage',
        'total_weight': 'totalWeight',
        'variety_id': 'varietyId',
        'variety_name': 'varietyName',
        'variety_unit': 'varietyUnit'
    }

    def __init__(self, crop_id=None, crop_name=None, loss_in_quantity=None, loss_percentage=None, total_weight=None, variety_id=None, variety_name=None, variety_unit=None):  # noqa: E501
        """HarvestLossPercentageDto - a model defined in Swagger"""  # noqa: E501
        self._crop_id = None
        self._crop_name = None
        self._loss_in_quantity = None
        self._loss_percentage = None
        self._total_weight = None
        self._variety_id = None
        self._variety_name = None
        self._variety_unit = None
        self.discriminator = None
        if crop_id is not None:
            self.crop_id = crop_id
        if crop_name is not None:
            self.crop_name = crop_name
        if loss_in_quantity is not None:
            self.loss_in_quantity = loss_in_quantity
        if loss_percentage is not None:
            self.loss_percentage = loss_percentage
        if total_weight is not None:
            self.total_weight = total_weight
        if variety_id is not None:
            self.variety_id = variety_id
        if variety_name is not None:
            self.variety_name = variety_name
        if variety_unit is not None:
            self.variety_unit = variety_unit

    @property
    def crop_id(self):
        """Gets the crop_id of this HarvestLossPercentageDto.  # noqa: E501


        :return: The crop_id of this HarvestLossPercentageDto.  # noqa: E501
        :rtype: int
        """
        return self._crop_id

    @crop_id.setter
    def crop_id(self, crop_id):
        """Sets the crop_id of this HarvestLossPercentageDto.


        :param crop_id: The crop_id of this HarvestLossPercentageDto.  # noqa: E501
        :type: int
        """

        self._crop_id = crop_id

    @property
    def crop_name(self):
        """Gets the crop_name of this HarvestLossPercentageDto.  # noqa: E501


        :return: The crop_name of this HarvestLossPercentageDto.  # noqa: E501
        :rtype: str
        """
        return self._crop_name

    @crop_name.setter
    def crop_name(self, crop_name):
        """Sets the crop_name of this HarvestLossPercentageDto.


        :param crop_name: The crop_name of this HarvestLossPercentageDto.  # noqa: E501
        :type: str
        """

        self._crop_name = crop_name

    @property
    def loss_in_quantity(self):
        """Gets the loss_in_quantity of this HarvestLossPercentageDto.  # noqa: E501


        :return: The loss_in_quantity of this HarvestLossPercentageDto.  # noqa: E501
        :rtype: float
        """
        return self._loss_in_quantity

    @loss_in_quantity.setter
    def loss_in_quantity(self, loss_in_quantity):
        """Sets the loss_in_quantity of this HarvestLossPercentageDto.


        :param loss_in_quantity: The loss_in_quantity of this HarvestLossPercentageDto.  # noqa: E501
        :type: float
        """

        self._loss_in_quantity = loss_in_quantity

    @property
    def loss_percentage(self):
        """Gets the loss_percentage of this HarvestLossPercentageDto.  # noqa: E501


        :return: The loss_percentage of this HarvestLossPercentageDto.  # noqa: E501
        :rtype: float
        """
        return self._loss_percentage

    @loss_percentage.setter
    def loss_percentage(self, loss_percentage):
        """Sets the loss_percentage of this HarvestLossPercentageDto.


        :param loss_percentage: The loss_percentage of this HarvestLossPercentageDto.  # noqa: E501
        :type: float
        """

        self._loss_percentage = loss_percentage

    @property
    def total_weight(self):
        """Gets the total_weight of this HarvestLossPercentageDto.  # noqa: E501


        :return: The total_weight of this HarvestLossPercentageDto.  # noqa: E501
        :rtype: float
        """
        return self._total_weight

    @total_weight.setter
    def total_weight(self, total_weight):
        """Sets the total_weight of this HarvestLossPercentageDto.


        :param total_weight: The total_weight of this HarvestLossPercentageDto.  # noqa: E501
        :type: float
        """

        self._total_weight = total_weight

    @property
    def variety_id(self):
        """Gets the variety_id of this HarvestLossPercentageDto.  # noqa: E501


        :return: The variety_id of this HarvestLossPercentageDto.  # noqa: E501
        :rtype: int
        """
        return self._variety_id

    @variety_id.setter
    def variety_id(self, variety_id):
        """Sets the variety_id of this HarvestLossPercentageDto.


        :param variety_id: The variety_id of this HarvestLossPercentageDto.  # noqa: E501
        :type: int
        """

        self._variety_id = variety_id

    @property
    def variety_name(self):
        """Gets the variety_name of this HarvestLossPercentageDto.  # noqa: E501


        :return: The variety_name of this HarvestLossPercentageDto.  # noqa: E501
        :rtype: str
        """
        return self._variety_name

    @variety_name.setter
    def variety_name(self, variety_name):
        """Sets the variety_name of this HarvestLossPercentageDto.


        :param variety_name: The variety_name of this HarvestLossPercentageDto.  # noqa: E501
        :type: str
        """

        self._variety_name = variety_name

    @property
    def variety_unit(self):
        """Gets the variety_unit of this HarvestLossPercentageDto.  # noqa: E501


        :return: The variety_unit of this HarvestLossPercentageDto.  # noqa: E501
        :rtype: str
        """
        return self._variety_unit

    @variety_unit.setter
    def variety_unit(self, variety_unit):
        """Sets the variety_unit of this HarvestLossPercentageDto.


        :param variety_unit: The variety_unit of this HarvestLossPercentageDto.  # noqa: E501
        :type: str
        """

        self._variety_unit = variety_unit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HarvestLossPercentageDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HarvestLossPercentageDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
