# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LanguageMaster(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'data': 'dict(str, object)',
        'description': 'str',
        'name': 'str'
    }

    attribute_map = {
        'code': 'code',
        'data': 'data',
        'description': 'description',
        'name': 'name'
    }

    def __init__(self, code=None, data=None, description=None, name=None):  # noqa: E501
        """LanguageMaster - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._data = None
        self._description = None
        self._name = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if data is not None:
            self.data = data
        if description is not None:
            self.description = description
        self.name = name

    @property
    def code(self):
        """Gets the code of this LanguageMaster.  # noqa: E501


        :return: The code of this LanguageMaster.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this LanguageMaster.


        :param code: The code of this LanguageMaster.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def data(self):
        """Gets the data of this LanguageMaster.  # noqa: E501


        :return: The data of this LanguageMaster.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this LanguageMaster.


        :param data: The data of this LanguageMaster.  # noqa: E501
        :type: dict(str, object)
        """

        self._data = data

    @property
    def description(self):
        """Gets the description of this LanguageMaster.  # noqa: E501


        :return: The description of this LanguageMaster.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this LanguageMaster.


        :param description: The description of this LanguageMaster.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this LanguageMaster.  # noqa: E501


        :return: The name of this LanguageMaster.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LanguageMaster.


        :param name: The name of this LanguageMaster.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LanguageMaster, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LanguageMaster):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
