# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LanguageTranslateDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'language': 'LanguageId',
        'translation': 'str'
    }

    attribute_map = {
        'language': 'language',
        'translation': 'translation'
    }

    def __init__(self, language=None, translation=None):  # noqa: E501
        """LanguageTranslateDto - a model defined in Swagger"""  # noqa: E501
        self._language = None
        self._translation = None
        self.discriminator = None
        if language is not None:
            self.language = language
        if translation is not None:
            self.translation = translation

    @property
    def language(self):
        """Gets the language of this LanguageTranslateDto.  # noqa: E501


        :return: The language of this LanguageTranslateDto.  # noqa: E501
        :rtype: LanguageId
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this LanguageTranslateDto.


        :param language: The language of this LanguageTranslateDto.  # noqa: E501
        :type: LanguageId
        """

        self._language = language

    @property
    def translation(self):
        """Gets the translation of this LanguageTranslateDto.  # noqa: E501


        :return: The translation of this LanguageTranslateDto.  # noqa: E501
        :rtype: str
        """
        return self._translation

    @translation.setter
    def translation(self, translation):
        """Sets the translation of this LanguageTranslateDto.


        :param translation: The translation of this LanguageTranslateDto.  # noqa: E501
        :type: str
        """

        self._translation = translation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LanguageTranslateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LanguageTranslateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
