# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlanDtoForBulkVarieties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plan_dto': 'PlanDto',
        'variety_rec_reference_date_map': 'dict(str, str)',
        'variety_reference_date_map': 'dict(str, str)'
    }

    attribute_map = {
        'plan_dto': 'planDto',
        'variety_rec_reference_date_map': 'varietyRecReferenceDateMap',
        'variety_reference_date_map': 'varietyReferenceDateMap'
    }

    def __init__(self, plan_dto=None, variety_rec_reference_date_map=None, variety_reference_date_map=None):  # noqa: E501
        """PlanDtoForBulkVarieties - a model defined in Swagger"""  # noqa: E501
        self._plan_dto = None
        self._variety_rec_reference_date_map = None
        self._variety_reference_date_map = None
        self.discriminator = None
        self.plan_dto = plan_dto
        if variety_rec_reference_date_map is not None:
            self.variety_rec_reference_date_map = variety_rec_reference_date_map
        if variety_reference_date_map is not None:
            self.variety_reference_date_map = variety_reference_date_map

    @property
    def plan_dto(self):
        """Gets the plan_dto of this PlanDtoForBulkVarieties.  # noqa: E501


        :return: The plan_dto of this PlanDtoForBulkVarieties.  # noqa: E501
        :rtype: PlanDto
        """
        return self._plan_dto

    @plan_dto.setter
    def plan_dto(self, plan_dto):
        """Sets the plan_dto of this PlanDtoForBulkVarieties.


        :param plan_dto: The plan_dto of this PlanDtoForBulkVarieties.  # noqa: E501
        :type: PlanDto
        """
        if plan_dto is None:
            raise ValueError("Invalid value for `plan_dto`, must not be `None`")  # noqa: E501

        self._plan_dto = plan_dto

    @property
    def variety_rec_reference_date_map(self):
        """Gets the variety_rec_reference_date_map of this PlanDtoForBulkVarieties.  # noqa: E501


        :return: The variety_rec_reference_date_map of this PlanDtoForBulkVarieties.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._variety_rec_reference_date_map

    @variety_rec_reference_date_map.setter
    def variety_rec_reference_date_map(self, variety_rec_reference_date_map):
        """Sets the variety_rec_reference_date_map of this PlanDtoForBulkVarieties.


        :param variety_rec_reference_date_map: The variety_rec_reference_date_map of this PlanDtoForBulkVarieties.  # noqa: E501
        :type: dict(str, str)
        """

        self._variety_rec_reference_date_map = variety_rec_reference_date_map

    @property
    def variety_reference_date_map(self):
        """Gets the variety_reference_date_map of this PlanDtoForBulkVarieties.  # noqa: E501


        :return: The variety_reference_date_map of this PlanDtoForBulkVarieties.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._variety_reference_date_map

    @variety_reference_date_map.setter
    def variety_reference_date_map(self, variety_reference_date_map):
        """Sets the variety_reference_date_map of this PlanDtoForBulkVarieties.


        :param variety_reference_date_map: The variety_reference_date_map of this PlanDtoForBulkVarieties.  # noqa: E501
        :type: dict(str, str)
        """

        self._variety_reference_date_map = variety_reference_date_map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanDtoForBulkVarieties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanDtoForBulkVarieties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
