# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlanTypePreference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'parent_prefernce_id': 'int',
        'plan_type_id': 'int',
        'preference': 'Preferences'
    }

    attribute_map = {
        'id': 'id',
        'parent_prefernce_id': 'parentPrefernceId',
        'plan_type_id': 'planTypeId',
        'preference': 'preference'
    }

    def __init__(self, id=None, parent_prefernce_id=None, plan_type_id=None, preference=None):  # noqa: E501
        """PlanTypePreference - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._parent_prefernce_id = None
        self._plan_type_id = None
        self._preference = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if parent_prefernce_id is not None:
            self.parent_prefernce_id = parent_prefernce_id
        if plan_type_id is not None:
            self.plan_type_id = plan_type_id
        if preference is not None:
            self.preference = preference

    @property
    def id(self):
        """Gets the id of this PlanTypePreference.  # noqa: E501


        :return: The id of this PlanTypePreference.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PlanTypePreference.


        :param id: The id of this PlanTypePreference.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def parent_prefernce_id(self):
        """Gets the parent_prefernce_id of this PlanTypePreference.  # noqa: E501


        :return: The parent_prefernce_id of this PlanTypePreference.  # noqa: E501
        :rtype: int
        """
        return self._parent_prefernce_id

    @parent_prefernce_id.setter
    def parent_prefernce_id(self, parent_prefernce_id):
        """Sets the parent_prefernce_id of this PlanTypePreference.


        :param parent_prefernce_id: The parent_prefernce_id of this PlanTypePreference.  # noqa: E501
        :type: int
        """

        self._parent_prefernce_id = parent_prefernce_id

    @property
    def plan_type_id(self):
        """Gets the plan_type_id of this PlanTypePreference.  # noqa: E501


        :return: The plan_type_id of this PlanTypePreference.  # noqa: E501
        :rtype: int
        """
        return self._plan_type_id

    @plan_type_id.setter
    def plan_type_id(self, plan_type_id):
        """Sets the plan_type_id of this PlanTypePreference.


        :param plan_type_id: The plan_type_id of this PlanTypePreference.  # noqa: E501
        :type: int
        """

        self._plan_type_id = plan_type_id

    @property
    def preference(self):
        """Gets the preference of this PlanTypePreference.  # noqa: E501


        :return: The preference of this PlanTypePreference.  # noqa: E501
        :rtype: Preferences
        """
        return self._preference

    @preference.setter
    def preference(self, preference):
        """Sets the preference of this PlanTypePreference.


        :param preference: The preference of this PlanTypePreference.  # noqa: E501
        :type: Preferences
        """

        self._preference = preference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanTypePreference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanTypePreference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
