# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Quantity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'float',
        'unit': 'str'
    }

    attribute_map = {
        'count': 'count',
        'unit': 'unit'
    }

    def __init__(self, count=None, unit=None):  # noqa: E501
        """Quantity - a model defined in Swagger"""  # noqa: E501
        self._count = None
        self._unit = None
        self.discriminator = None
        if count is not None:
            self.count = count
        if unit is not None:
            self.unit = unit

    @property
    def count(self):
        """Gets the count of this Quantity.  # noqa: E501


        :return: The count of this Quantity.  # noqa: E501
        :rtype: float
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this Quantity.


        :param count: The count of this Quantity.  # noqa: E501
        :type: float
        """

        self._count = count

    @property
    def unit(self):
        """Gets the unit of this Quantity.  # noqa: E501


        :return: The unit of this Quantity.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this Quantity.


        :param unit: The unit of this Quantity.  # noqa: E501
        :type: str
        """
        allowed_values = ["GRAM", "KILOGRAM", "TON", "METRIC_TON", "POUND", "OUNCE", "LITRE", "QUINTAL", "LIQUID_OUNCE", "GALLON", "NUMBER_OF_PLANTS", "DOSE"]  # noqa: E501
        if unit not in allowed_values:
            raise ValueError(
                "Invalid value for `unit` ({0}), must be one of {1}"  # noqa: E501
                .format(unit, allowed_values)
            )

        self._unit = unit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Quantity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Quantity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
