# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SKUTypeDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'capacity': 'float',
        'client_id': 'str',
        'data': 'dict(str, object)',
        'description': 'str',
        'id': 'int',
        'name': 'str',
        'unit_id': 'int'
    }

    attribute_map = {
        'capacity': 'capacity',
        'client_id': 'clientId',
        'data': 'data',
        'description': 'description',
        'id': 'id',
        'name': 'name',
        'unit_id': 'unitId'
    }

    def __init__(self, capacity=None, client_id=None, data=None, description=None, id=None, name=None, unit_id=None):  # noqa: E501
        """SKUTypeDTO - a model defined in Swagger"""  # noqa: E501
        self._capacity = None
        self._client_id = None
        self._data = None
        self._description = None
        self._id = None
        self._name = None
        self._unit_id = None
        self.discriminator = None
        if capacity is not None:
            self.capacity = capacity
        if client_id is not None:
            self.client_id = client_id
        if data is not None:
            self.data = data
        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        self.name = name
        self.unit_id = unit_id

    @property
    def capacity(self):
        """Gets the capacity of this SKUTypeDTO.  # noqa: E501


        :return: The capacity of this SKUTypeDTO.  # noqa: E501
        :rtype: float
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this SKUTypeDTO.


        :param capacity: The capacity of this SKUTypeDTO.  # noqa: E501
        :type: float
        """

        self._capacity = capacity

    @property
    def client_id(self):
        """Gets the client_id of this SKUTypeDTO.  # noqa: E501


        :return: The client_id of this SKUTypeDTO.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this SKUTypeDTO.


        :param client_id: The client_id of this SKUTypeDTO.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def data(self):
        """Gets the data of this SKUTypeDTO.  # noqa: E501


        :return: The data of this SKUTypeDTO.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SKUTypeDTO.


        :param data: The data of this SKUTypeDTO.  # noqa: E501
        :type: dict(str, object)
        """

        self._data = data

    @property
    def description(self):
        """Gets the description of this SKUTypeDTO.  # noqa: E501


        :return: The description of this SKUTypeDTO.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SKUTypeDTO.


        :param description: The description of this SKUTypeDTO.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this SKUTypeDTO.  # noqa: E501


        :return: The id of this SKUTypeDTO.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SKUTypeDTO.


        :param id: The id of this SKUTypeDTO.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SKUTypeDTO.  # noqa: E501


        :return: The name of this SKUTypeDTO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SKUTypeDTO.


        :param name: The name of this SKUTypeDTO.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def unit_id(self):
        """Gets the unit_id of this SKUTypeDTO.  # noqa: E501


        :return: The unit_id of this SKUTypeDTO.  # noqa: E501
        :rtype: int
        """
        return self._unit_id

    @unit_id.setter
    def unit_id(self, unit_id):
        """Sets the unit_id of this SKUTypeDTO.


        :param unit_id: The unit_id of this SKUTypeDTO.  # noqa: E501
        :type: int
        """
        if unit_id is None:
            raise ValueError("Invalid value for `unit_id`, must not be `None`")  # noqa: E501

        self._unit_id = unit_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SKUTypeDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SKUTypeDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
