# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SplitCropUnitsDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'croppable_area_id': 'int',
        'name_prefix': 'str'
    }

    attribute_map = {
        'count': 'count',
        'croppable_area_id': 'croppableAreaId',
        'name_prefix': 'namePrefix'
    }

    def __init__(self, count=None, croppable_area_id=None, name_prefix=None):  # noqa: E501
        """SplitCropUnitsDto - a model defined in Swagger"""  # noqa: E501
        self._count = None
        self._croppable_area_id = None
        self._name_prefix = None
        self.discriminator = None
        if count is not None:
            self.count = count
        if croppable_area_id is not None:
            self.croppable_area_id = croppable_area_id
        if name_prefix is not None:
            self.name_prefix = name_prefix

    @property
    def count(self):
        """Gets the count of this SplitCropUnitsDto.  # noqa: E501


        :return: The count of this SplitCropUnitsDto.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this SplitCropUnitsDto.


        :param count: The count of this SplitCropUnitsDto.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def croppable_area_id(self):
        """Gets the croppable_area_id of this SplitCropUnitsDto.  # noqa: E501


        :return: The croppable_area_id of this SplitCropUnitsDto.  # noqa: E501
        :rtype: int
        """
        return self._croppable_area_id

    @croppable_area_id.setter
    def croppable_area_id(self, croppable_area_id):
        """Sets the croppable_area_id of this SplitCropUnitsDto.


        :param croppable_area_id: The croppable_area_id of this SplitCropUnitsDto.  # noqa: E501
        :type: int
        """

        self._croppable_area_id = croppable_area_id

    @property
    def name_prefix(self):
        """Gets the name_prefix of this SplitCropUnitsDto.  # noqa: E501


        :return: The name_prefix of this SplitCropUnitsDto.  # noqa: E501
        :rtype: str
        """
        return self._name_prefix

    @name_prefix.setter
    def name_prefix(self, name_prefix):
        """Sets the name_prefix of this SplitCropUnitsDto.


        :param name_prefix: The name_prefix of this SplitCropUnitsDto.  # noqa: E501
        :type: str
        """

        self._name_prefix = name_prefix

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SplitCropUnitsDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SplitCropUnitsDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
