# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CUVarietyDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crop_variety_name': 'str',
        'row_num': 'int'
    }

    attribute_map = {
        'crop_variety_name': 'cropVarietyName',
        'row_num': 'rowNum'
    }

    def __init__(self, crop_variety_name=None, row_num=None):  # noqa: E501
        """CUVarietyDto - a model defined in Swagger"""  # noqa: E501
        self._crop_variety_name = None
        self._row_num = None
        self.discriminator = None
        if crop_variety_name is not None:
            self.crop_variety_name = crop_variety_name
        if row_num is not None:
            self.row_num = row_num

    @property
    def crop_variety_name(self):
        """Gets the crop_variety_name of this CUVarietyDto.  # noqa: E501


        :return: The crop_variety_name of this CUVarietyDto.  # noqa: E501
        :rtype: str
        """
        return self._crop_variety_name

    @crop_variety_name.setter
    def crop_variety_name(self, crop_variety_name):
        """Sets the crop_variety_name of this CUVarietyDto.


        :param crop_variety_name: The crop_variety_name of this CUVarietyDto.  # noqa: E501
        :type: str
        """

        self._crop_variety_name = crop_variety_name

    @property
    def row_num(self):
        """Gets the row_num of this CUVarietyDto.  # noqa: E501


        :return: The row_num of this CUVarietyDto.  # noqa: E501
        :rtype: int
        """
        return self._row_num

    @row_num.setter
    def row_num(self, row_num):
        """Sets the row_num of this CUVarietyDto.


        :param row_num: The row_num of this CUVarietyDto.  # noqa: E501
        :type: int
        """

        self._row_num = row_num

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CUVarietyDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CUVarietyDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
