# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlanDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_id': 'str',
        'current_plan': 'bool',
        'data': 'dict(str, object)',
        'deleted': 'bool',
        'description': 'str',
        'id': 'int',
        'images': 'dict(str, object)',
        'name': 'str',
        'parent_plan': 'int',
        'plan_type_id': 'int',
        'plan_type_name': 'str',
        'po_p': 'PoPDto',
        'schedule': 'Schedule',
        'varieties': 'list[int]',
        'version': 'int'
    }

    attribute_map = {
        'client_id': 'clientId',
        'current_plan': 'currentPlan',
        'data': 'data',
        'deleted': 'deleted',
        'description': 'description',
        'id': 'id',
        'images': 'images',
        'name': 'name',
        'parent_plan': 'parentPlan',
        'plan_type_id': 'planTypeId',
        'plan_type_name': 'planTypeName',
        'po_p': 'poP',
        'schedule': 'schedule',
        'varieties': 'varieties',
        'version': 'version'
    }

    def __init__(self, client_id=None, current_plan=None, data=None, deleted=None, description=None, id=None, images=None, name=None, parent_plan=None, plan_type_id=None, plan_type_name=None, po_p=None, schedule=None, varieties=None, version=None):  # noqa: E501
        """PlanDto - a model defined in Swagger"""  # noqa: E501
        self._client_id = None
        self._current_plan = None
        self._data = None
        self._deleted = None
        self._description = None
        self._id = None
        self._images = None
        self._name = None
        self._parent_plan = None
        self._plan_type_id = None
        self._plan_type_name = None
        self._po_p = None
        self._schedule = None
        self._varieties = None
        self._version = None
        self.discriminator = None
        if client_id is not None:
            self.client_id = client_id
        if current_plan is not None:
            self.current_plan = current_plan
        if data is not None:
            self.data = data
        if deleted is not None:
            self.deleted = deleted
        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        if images is not None:
            self.images = images
        self.name = name
        if parent_plan is not None:
            self.parent_plan = parent_plan
        self.plan_type_id = plan_type_id
        if plan_type_name is not None:
            self.plan_type_name = plan_type_name
        if po_p is not None:
            self.po_p = po_p
        if schedule is not None:
            self.schedule = schedule
        if varieties is not None:
            self.varieties = varieties
        if version is not None:
            self.version = version

    @property
    def client_id(self):
        """Gets the client_id of this PlanDto.  # noqa: E501


        :return: The client_id of this PlanDto.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this PlanDto.


        :param client_id: The client_id of this PlanDto.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def current_plan(self):
        """Gets the current_plan of this PlanDto.  # noqa: E501


        :return: The current_plan of this PlanDto.  # noqa: E501
        :rtype: bool
        """
        return self._current_plan

    @current_plan.setter
    def current_plan(self, current_plan):
        """Sets the current_plan of this PlanDto.


        :param current_plan: The current_plan of this PlanDto.  # noqa: E501
        :type: bool
        """

        self._current_plan = current_plan

    @property
    def data(self):
        """Gets the data of this PlanDto.  # noqa: E501


        :return: The data of this PlanDto.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this PlanDto.


        :param data: The data of this PlanDto.  # noqa: E501
        :type: dict(str, object)
        """

        self._data = data

    @property
    def deleted(self):
        """Gets the deleted of this PlanDto.  # noqa: E501


        :return: The deleted of this PlanDto.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this PlanDto.


        :param deleted: The deleted of this PlanDto.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def description(self):
        """Gets the description of this PlanDto.  # noqa: E501


        :return: The description of this PlanDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PlanDto.


        :param description: The description of this PlanDto.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this PlanDto.  # noqa: E501


        :return: The id of this PlanDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PlanDto.


        :param id: The id of this PlanDto.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def images(self):
        """Gets the images of this PlanDto.  # noqa: E501


        :return: The images of this PlanDto.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this PlanDto.


        :param images: The images of this PlanDto.  # noqa: E501
        :type: dict(str, object)
        """

        self._images = images

    @property
    def name(self):
        """Gets the name of this PlanDto.  # noqa: E501


        :return: The name of this PlanDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PlanDto.


        :param name: The name of this PlanDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def parent_plan(self):
        """Gets the parent_plan of this PlanDto.  # noqa: E501


        :return: The parent_plan of this PlanDto.  # noqa: E501
        :rtype: int
        """
        return self._parent_plan

    @parent_plan.setter
    def parent_plan(self, parent_plan):
        """Sets the parent_plan of this PlanDto.


        :param parent_plan: The parent_plan of this PlanDto.  # noqa: E501
        :type: int
        """

        self._parent_plan = parent_plan

    @property
    def plan_type_id(self):
        """Gets the plan_type_id of this PlanDto.  # noqa: E501


        :return: The plan_type_id of this PlanDto.  # noqa: E501
        :rtype: int
        """
        return self._plan_type_id

    @plan_type_id.setter
    def plan_type_id(self, plan_type_id):
        """Sets the plan_type_id of this PlanDto.


        :param plan_type_id: The plan_type_id of this PlanDto.  # noqa: E501
        :type: int
        """
        if plan_type_id is None:
            raise ValueError("Invalid value for `plan_type_id`, must not be `None`")  # noqa: E501

        self._plan_type_id = plan_type_id

    @property
    def plan_type_name(self):
        """Gets the plan_type_name of this PlanDto.  # noqa: E501


        :return: The plan_type_name of this PlanDto.  # noqa: E501
        :rtype: str
        """
        return self._plan_type_name

    @plan_type_name.setter
    def plan_type_name(self, plan_type_name):
        """Sets the plan_type_name of this PlanDto.


        :param plan_type_name: The plan_type_name of this PlanDto.  # noqa: E501
        :type: str
        """

        self._plan_type_name = plan_type_name

    @property
    def po_p(self):
        """Gets the po_p of this PlanDto.  # noqa: E501


        :return: The po_p of this PlanDto.  # noqa: E501
        :rtype: PoPDto
        """
        return self._po_p

    @po_p.setter
    def po_p(self, po_p):
        """Sets the po_p of this PlanDto.


        :param po_p: The po_p of this PlanDto.  # noqa: E501
        :type: PoPDto
        """

        self._po_p = po_p

    @property
    def schedule(self):
        """Gets the schedule of this PlanDto.  # noqa: E501


        :return: The schedule of this PlanDto.  # noqa: E501
        :rtype: Schedule
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this PlanDto.


        :param schedule: The schedule of this PlanDto.  # noqa: E501
        :type: Schedule
        """

        self._schedule = schedule

    @property
    def varieties(self):
        """Gets the varieties of this PlanDto.  # noqa: E501


        :return: The varieties of this PlanDto.  # noqa: E501
        :rtype: list[int]
        """
        return self._varieties

    @varieties.setter
    def varieties(self, varieties):
        """Sets the varieties of this PlanDto.


        :param varieties: The varieties of this PlanDto.  # noqa: E501
        :type: list[int]
        """

        self._varieties = varieties

    @property
    def version(self):
        """Gets the version of this PlanDto.  # noqa: E501


        :return: The version of this PlanDto.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this PlanDto.


        :param version: The version of this PlanDto.  # noqa: E501
        :type: int
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
