# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScheduleDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_id': 'str',
        'data': 'dict(str, object)',
        'id': 'int',
        'name': 'str',
        'plan_id': 'int',
        'plan_name': 'str'
    }

    attribute_map = {
        'client_id': 'clientId',
        'data': 'data',
        'id': 'id',
        'name': 'name',
        'plan_id': 'planId',
        'plan_name': 'planName'
    }

    def __init__(self, client_id=None, data=None, id=None, name=None, plan_id=None, plan_name=None):  # noqa: E501
        """ScheduleDto - a model defined in Swagger"""  # noqa: E501
        self._client_id = None
        self._data = None
        self._id = None
        self._name = None
        self._plan_id = None
        self._plan_name = None
        self.discriminator = None
        if client_id is not None:
            self.client_id = client_id
        if data is not None:
            self.data = data
        if id is not None:
            self.id = id
        self.name = name
        if plan_id is not None:
            self.plan_id = plan_id
        if plan_name is not None:
            self.plan_name = plan_name

    @property
    def client_id(self):
        """Gets the client_id of this ScheduleDto.  # noqa: E501


        :return: The client_id of this ScheduleDto.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this ScheduleDto.


        :param client_id: The client_id of this ScheduleDto.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def data(self):
        """Gets the data of this ScheduleDto.  # noqa: E501


        :return: The data of this ScheduleDto.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ScheduleDto.


        :param data: The data of this ScheduleDto.  # noqa: E501
        :type: dict(str, object)
        """

        self._data = data

    @property
    def id(self):
        """Gets the id of this ScheduleDto.  # noqa: E501


        :return: The id of this ScheduleDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ScheduleDto.


        :param id: The id of this ScheduleDto.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ScheduleDto.  # noqa: E501


        :return: The name of this ScheduleDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ScheduleDto.


        :param name: The name of this ScheduleDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def plan_id(self):
        """Gets the plan_id of this ScheduleDto.  # noqa: E501


        :return: The plan_id of this ScheduleDto.  # noqa: E501
        :rtype: int
        """
        return self._plan_id

    @plan_id.setter
    def plan_id(self, plan_id):
        """Sets the plan_id of this ScheduleDto.


        :param plan_id: The plan_id of this ScheduleDto.  # noqa: E501
        :type: int
        """

        self._plan_id = plan_id

    @property
    def plan_name(self):
        """Gets the plan_name of this ScheduleDto.  # noqa: E501


        :return: The plan_name of this ScheduleDto.  # noqa: E501
        :rtype: str
        """
        return self._plan_name

    @plan_name.setter
    def plan_name(self, plan_name):
        """Sets the plan_name of this ScheduleDto.


        :param plan_name: The plan_name of this ScheduleDto.  # noqa: E501
        :type: str
        """

        self._plan_name = plan_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScheduleDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduleDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
