
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-28T15:40:30-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "539ebcec650e4be604033d99074571e4413503f6",
 "version": "0.1.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
