# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import plotrisk_python_client
from plotrisk_python_client.models.available_assets_dto import AvailableAssetsDto  # noqa: E501
from plotrisk_python_client.rest import ApiException


class TestAvailableAssetsDto(unittest.TestCase):
    """AvailableAssetsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableAssetsDto(self):
        """Test AvailableAssetsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = plotrisk_python_client.models.available_assets_dto.AvailableAssetsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
