# coding: utf-8

"""
    farm API

    farm API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import plotrisk_python_client
from plotrisk_python_client.models.preferences import Preferences  # noqa: E501
from plotrisk_python_client.rest import ApiException


class TestPreferences(unittest.TestCase):
    """Preferences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreferences(self):
        """Test Preferences"""
        # FIXME: construct object with mandatory attributes with example values
        # model = plotrisk_python_client.models.preferences.Preferences()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
