
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-29T17:21:57+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "bcab83d03037749216b9687f223f19dc99bdc206",
 "version": "v3.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
