# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10jobservice.proto\x12\njobservice\"F\n\x11JobServiceRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\njob_set_id\x18\x02 \x01(\t\x12\r\n\x05queue\x18\x03 \x01(\t\"\xd2\x01\n\x12JobServiceResponse\x12\x33\n\x05state\x18\x01 \x01(\x0e\x32$.jobservice.JobServiceResponse.State\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"x\n\x05State\x12\r\n\tSUBMITTED\x10\x00\x12\x13\n\x0f\x44UPLICATE_FOUND\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\r\n\tSUCCEEDED\x10\x04\x12\r\n\tCANCELLED\x10\x05\x12\x14\n\x10JOB_ID_NOT_FOUND\x10\x06\x32]\n\nJobService\x12O\n\x0cGetJobStatus\x12\x1d.jobservice.JobServiceRequest\x1a\x1e.jobservice.JobServiceResponse\"\x00\x42\x1e\xaa\x02\x1b\x41rmadaProject.Io.JobServiceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jobservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\033ArmadaProject.Io.JobService'
  _JOBSERVICEREQUEST._serialized_start=32
  _JOBSERVICEREQUEST._serialized_end=102
  _JOBSERVICERESPONSE._serialized_start=105
  _JOBSERVICERESPONSE._serialized_end=315
  _JOBSERVICERESPONSE_STATE._serialized_start=195
  _JOBSERVICERESPONSE_STATE._serialized_end=315
  _JOBSERVICE._serialized_start=317
  _JOBSERVICE._serialized_end=410
# @@protoc_insertion_point(module_scope)
