
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-27T06:43:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "28412902fa0e23676f49a0aab84ee5248528a26f",
 "version": "1.17.1.post0.dev149"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
